### ISSUE TITLE
Change prefix from `@`

### ISSUE THREAD

**Issue by spwhitton** [vermiculus/magithub#10]
Hello,

The well-established [magit-annex](https://github.com/magit/magit-annex) package uses the `@` prefix.  Please consider using something else.

Thanks.

**Comment by vermiculus** [comment]
Oh, sorry! I'd be happy to. Any suggestions?

**Comment by spwhitton** [comment]
Well, `?` duplicates `h` so you could override `h`.

**Comment by vermiculus** [comment]
Hm, I'd rather not – `h` and `?` are both canonical for 'help'. It's an option, but do you have any other suggestions?

I'm going through a list now of packages that add to the dispatcher (at least in the same way I do).

**Comment by vermiculus** [comment]
@tarsius – would you be alright if I overwrote `h`? I'm not finding any good alternatives 😢

**Comment by aspiers** [comment]
The old magithub used `#` and I think that's a pretty good choice given that github uses `#` to refer to pull requests and issues, e.g. #10.

**Comment by vermiculus** [comment]
[Already in use](https://github.com/sigma/magit-gh-pulls/blob/master/magit-gh-pulls.el)

**Comment by tarsius** [comment]
> would you be alright if I overwrote `h`?

No, it's default binding is important for beginners!

**Comment by aspiers** [comment]
Ah sorry, I was confusing the old magithub with `magit-gh-pulls` (which I already have installed). I guess some people would want both of these packages installed at the same time, if they offer slightly different functionality.  How about another punctuation mark, e.g. `%` ?

**Comment by aspiers** [comment]
Or `H`?

**Comment by vermiculus** [comment]
`H` is a hard key to press (at least for me) and `%` similarly has the left hand move pretty far to reach it (and also has no useful mnemonic).

I've been able to make this customizable (it will be pushed soon) but we should find a good default. In the void of anything better, I'll change to `H` for now.

> No, its default binding is important for beginners!

Yep, just wanted to make sure :-)

**Comment by spwhitton** [comment]
On Sun, Sep 18, 2016 at 10:04:21AM -0700, Sean Allred wrote:
> Hm, I'd rather not – h and ? are both canonical for 'help'. It's an option, but
> do you have any other suggestions?

It might be worth making a list of all the ones that are not used by
core magit.

> I'm going through a list now of packages that add to the dispatcher
> (at least in the same way I do).

... and a corresponding list of those used by plugins.

This could be published somewhere and linked to from the magit
documentation.

-- 
Sean Whitton

**Comment by vermiculus** [comment]
> and a corresponding list of those used by plugins

The difficulty with that (as I've learned this morning) is that it seems like everyone and their mother tracks the actual packages they use – I get a *lot* of duplicates and more than a few one-offs.

Such a list maintained as a courtesy would be good though – something like [the LaTeX3 prefix registry](https://github.com/latex3/latex3/blob/master/l3kernel/l3prefixes.csv) ([and see](http://tex.stackexchange.com/a/115909/17423)) could serve as an authoritative source – anything not in there is fair game.

That would be best raised on magit/magit, though.

**Comment by aspiers** [comment]
Great idea! Submitted as https://github.com/magit/magit/issues/2779

**Comment by vermiculus** [comment]
I've bound it to `H` and introduced the ability to customize the key. There are some issues when you change it and use it in the same session (`Magithub` will appear twice in the dispatcher), but I think that's acceptable for now.
