### ISSUE TITLE
Username getting inserted into base branch.

### ISSUE THREAD

**Issue by pbogdan** [vermiculus/magithub#102]
I'm not quite sure whether I'm doing something wrong but it seems that my user name gets inserted into the base branch which then errors out when making API call.
When submitting a test PR I picked "master" as the base branch and "test" as the head yet in the dialog that follows I see:

```
PR pbogdan/ngx-top (pbogdan:test->master)
```

and the error:

```
Unprocessable Entity: "POST", "/repos/pbogdan/ngx-top/pulls", nil, "{\"maintainer_can_modify\":true,\"title\":\"test\",\"body\":\"\",\"base\":\"master\",\"head\":\"pbogdan:test\"}", ((message . "Validation Failed") (errors ((resource . "PullRequest") (field . "head") (code . "invalid"))) (documentation_url . "https://developer.github.com/v3/pulls/#create-a-pull-request"))
```

Am I perhaps misunderstanding how to specify base branch and the head?

I tested with `emacs -Q` as well and loading just magit / magithub but the error persists.

**Comment by vermiculus** [comment]
According to [the documentation](https://developer.github.com/v3/pulls/#create-a-pull-request), `head` is formatted appropriately. Did you push branch `test`?

**Comment by pbogdan** [comment]
I pushed the branch, yes. Unless I'm misunderstanding the documentation it sounds as if it shouldn't be prefixed in this case since both branches are in the same repo.

**Comment by vermiculus** [comment]
Hm, you're right. Looks like the definition of `magithub-pull-request-new` will have to be modified to not namespace the username if `base` belongs to that same username. Thanks for the report!

I won't have access to any tech for the next few weeks (going on vacation), so unfortunately nothing will happen on this until June 10 ☹️

**Comment by pbogdan** [comment]
No worries, will take a stab at fixing this but my git / elisp skills are lacking to say the least.. Enjoy your vacation 😄
