### ISSUE TITLE
Better Compatibility with `authinfo.gpg`?

### ISSUE THREAD

**Issue by LdBeth** [vermiculus/magithub#103]
I use `authinfo.gpg`, a GPG encrypted `authinfo` file, to manage my passwords in Emacs.
Thou I've configured `gpg-agent` to cache the main password, running Magithub before the first time the password is entered would cause connection to GitHub API timeout. 

If it is possible to make Magithub waiting GPG's password prompt before connect to GtHub API or it is actually a upstream issue of `ghub`?

**Comment by vermiculus** [comment]
Magithub itself doesn't handle any authentication, so this is an upstream issue.

**Comment by LdBeth** [comment]
Thanks. I'll report it upstream.

**Comment by LdBeth** [comment]
Sorry for reopen this issue, but I find that this snippet caused the my problem.

`magithub-core.el: line 142`

```
(let* (error-data
             (response (with-timeout (magithub-api-timeout :timeout)
                         (condition-case err (ghub-get "/rate_limit")
                           (error (setq error-data err) :errored-out))))
```
`ghub.el` prompts for the password if `authinfo` is encrypted when `ghub-get` is called, but `magithub` doesn't wait for users to input the password. If they can't input the password before `magithub-api-timeout`, an error of timeout would appear.

I wonder if it is possible to modify the above snippet to this:
``` 
(let* (error-data
       (response (if (= magithub-api-timeout 0)
                     (progn
                       (with-timeout (magithub-api-timeout :timeout)
                         (condition-case err (ghub-get "/rate_limit")
                           (error (setq error-data err) :errored-out))))
                   (ghub-get "/rate_limit"))))
```

Then if `magithub-api-timeout` is `0`, timeout will be ignored.

After all, if there is no Internet connected, another error would be catch and `magithub` can go offline.

**Comment by vermiculus** [comment]
Nice catch.

Hm… I'm not sure how I feel about your snippet (since any value instead of `0` (including `0`) is somewhat arbitrary). I'm wondering if there's any way to pause the clock for the timeout while you're putting in your password.

Other than that – we could also just try unlocking your authinfo before calling this code. When emacs asks you for your password, this info is cached, yes? If you ask authinfo for credentials to another account, does Emacs asks you for your authinfo password again?

**Comment by vermiculus** [comment]
I'm currently unable to get gpg-agent to cooperate with me on this one – it may take me some time to fix it.

If you can provide a snippet though that will do the following though, I can insert it (or you can in a PR) at `magithub--api-available-p` right before the first `let`.

1. Check if the auth-source with the necessary keys is encrypted.
1. If it's encrypted, decrypt it (not asking for any particular credential) before moving on.

**Comment by dmin7b5** [comment]
I'm using authinfo.gpg with no issues so far on first pwd prompt.  I also set ~/.gnupg/gpg-agent.conf vars default-cache-ttl, max-cache-ttl to 34560000 so it won't time out on me.

**Comment by vermiculus** [comment]
I was over-complicating this. Commit incoming 😄
