### ISSUE TITLE
(void-function unfill-region) — magithub should list unfill.el as dependency?

### ISSUE THREAD

**Issue by deprecated** [vermiculus/magithub#11]
Hi - this looks like a very useful package.  I just installed it from MELPA and then tried to use it to open a new issue against one of my repos.  But, I got the following error: 
```
(void-function unfill-region)
```
which comes from a hook that you add to `with-editor-finish` in your function `magithub-check-buffer`. 

Is this a new function in emacs 25?  I am still on emacs 24:
```
GNU Emacs 24.5.2 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
```

I see there is a third party `unfill` package - I will try using that.  Maybe this should be listed as a dependency on MELPA

**Comment by vermiculus** [comment]
Whoops! See above. 😃

**Comment by vermiculus** [comment]
Although it does look like unfill.el would work as a drop-in replacement.
