### ISSUE TITLE
Turn Magithub off for non GitHub Repositorys

### ISSUE THREAD

**Issue by r00tbox** [vermiculus/magithub#110]
I use a lot of selfhosted repositorys at work, and magit want to connect all the time to github. 

Is it possible to turn it off for non github repos?
Or turn it on for github repos?

If it's not possible right now take this as a FR ;-)

**Comment by vermiculus** [comment]
If you open the magithub popup, you can turn it off for that repository via a git property (`M-x magithub-enabled-toggle`).

It should be autodetecting github domains, though -- can you tell me what `(magit-get "remote" "origin" "url")` returns?

**Comment by r00tbox** [comment]
The `magithub-enable-toggle` is a permanent setting?

`"benedikt@10.*.*.*:/git/config/Tools"` is the return of `(magit-get "remote" "origin" "url")`

**Comment by vermiculus** [comment]
It is permanent per-repo, yes.

**Comment by vermiculus** [comment]
Can you confirm if the issue still happens for you after the recent merge?

**Comment by vermiculus** [comment]
Closing as no longer an issue.
