### ISSUE TITLE
Support Private Repos In Organizations

### ISSUE THREAD

**Issue by dmin7b5** [vermiculus/magithub#114]
I've tried using orgname/reponame but I get an invalid name error.  And I'm not sure how I would indicate I want a private repo created.  In hub I use:  hub create orgname/reponame -p -d "Repo Description"

**Comment by vermiculus** [comment]
Can you provide the exact error text?

**Comment by dmin7b5** [comment]
when prompted with: Repository name: myusername/orgname/reponame + <enter> I get, "invalid name".  Not sure what syntax to use for a private repo on an org.

**Comment by vermiculus** [comment]
Should it not just be orgname/reponame?

Sorry, I'm not that familiar with organizations.

**Comment by dmin7b5** [comment]
Sorry, yes...if you try to delete the myusername part that is pre-populated in the prompt, you get an error saying, "Text is read-only".

**Comment by vermiculus** [comment]
Ahh... I gotcha now. I'll see what I can do for this. Probably before we prompt, we should get a list of all accounts to which the user has push access -- *then* use that for the prompt.

**Comment by dmin7b5** [comment]
ya that would be great, or If we could change that text and do something like orgname/reponame -p (and any other valid hub flags) that would be awesome.

**Comment by vermiculus** [comment]
I'll see what I can do about creating private repositories. The interface for homepage/description might be a little more complicated.

**Comment by dmin7b5** [comment]
Thanks for looking at this...I love what you are doing with magithub.  I really enjoy not having to constantly toggle to iterm and back to emacs...you rock!

**Comment by vermiculus** [comment]
@dmin7b5 Can you try out the `develop` branch? I'm not a member of any organizations so I can't rightly test to see if my changes really work 😉

**Comment by dmin7b5** [comment]
Ok, I just tried it out.  I was not certain what the best practices are for using github packages in spacemacs so here is what I did.  I manually cloned the repo and checked out the develop branch.  I backed up my ~/.emacs.d/elpa/magithub-20170730.723 folder.  I deleted the files in the folder and replaced them with the develop branch ones.  I then restarted Spacemacs and it said it was installing a new package.  So I've got a local test repo containing 1 text file and 1 commit.  When first using "H" and "c" for creating on github, I am still prompted with:  Repository name: gitusername/

I looked at your commit and see where it should be asking for my username first.  For some reason I'm not getting that far.  So it may be the (unless (or (magithub-github-repository-p) stuff...dunno

**Comment by vermiculus** [comment]
Alrighty, try again. I tested with creating a private repo myself and everything seems to be in order; just the org stuff remains untested.

Note you'll need the most recent version of ghub+.

**Comment by dmin7b5** [comment]
So I was able to push to an org with a private repo successfully.  Some things to note though.  I had to add (magithub-feature-autoinject t) to my user-config section of init.el because I kept getting this message popping up in between steps:  "Magithub features not configured (pull-request-merge pull-request-checkout) ; see variable  ‘magithub-features’ to turn off this message".  Once I added that and restarted Spacemacs it went away.

After hitting "u" in the final step to push everything up, I get the message, "API not responding quickly, go offline? (y or n)".  I kept hitting "n" and after about 4 of those messages it went away and I could see the commit had worked.

Just an fyi on what versions of stuff I'm using:  Emacs (spacemacs) 25.2 with latest pkgs, hub version 2.3.0-pre10.

Thanks for getting this working, it's awesome!

**Comment by vermiculus** [comment]
API offline stuff related to #107.

Re `magithub-feature-autoinject`; [see the README](https://github.com/vermiculus/magithub#installation).

I'm glad stuff is working for you!

**Comment by dmin7b5** [comment]
Thanks for the links.  Yeah, I'm using gpg so that's why the message is popping up.  I've been testing it and it your code is working every time.  The only odd thing now is that after everything is completed, the last line after the commit info says:  "CI:       Pending  (it seems checks have not yet begun)".

**Comment by vermiculus** [comment]
@dmin7b5 That's to be expected; it takes time for GitHub to notify the CI of the push and for the CI to start the checks. That time is way longer than it takes us to ask for the statuses of the ref we *just* pushed, so the response comes back null.

I'm unsure of how to handle this without being annoying -- the only thing I can think of is to have some sort of idle-timer hook that'll refresh CI-status, but that'll kick off a full magit-refresh which would probably interrupt any other staging/committing work being done.

**Comment by dmin7b5** [comment]
Good point.  Perhaps being more explicit with the notification would suffice, "CI: Pending (awaiting host notification to allow the CI checking process to begin)"

**Comment by vermiculus** [comment]
@dmin7b5 [When the header is being calculated](https://github.com/vermiculus/magithub/blob/master/magithub-ci.el#L211), though, we can't tell between the following possibilities:
* GitHub hasn't sent a notification to CI
* CI hasn't responded to the notification
* CI hasn't created the build ticket and inserted it into the queue
* CI hasn't gotten to the ticket in the queue
* CI hasn't started the build
* CI hasn't sent GitHub a notification of the build-start
* GitHub hasn't processed this notification
Trying to be too specific here isn't the answer -- if anything, the message should be more generic.

This conversation might be better suited to a new issue, though.
