### ISSUE TITLE
checking out pull request fails

### ISSUE THREAD

**Issue by wbolster** [vermiculus/magithub#117]
i just noticed that this awesome package provides a way to checkout a pull request branch locally by using `bP` in a `magit-status` buffer.

however, it fails with this error for me:

```
Debugger entered--Lisp error: (wrong-type-argument stringp 19)
  call-process("git" nil nil nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "config" "branch.search-commands.magithubPullRequestID" 19)
  apply(call-process "git" nil nil nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "config" "branch.search-commands.magithubPullRequestID" 19))
  process-file("git" nil nil nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "config" "branch.search-commands.magithubPullRequestID" 19)
  apply(process-file ("git" nil nil nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "config" "branch.search-commands.magithubPullRequestID" 19))
  magit-process-file("git" nil nil nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "config" "branch.search-commands.magithubPullRequestID" 19)
  apply(magit-process-file "git" nil nil nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "config" "branch.search-commands.magithubPullRequestID" 19))
  magit-git-exit-code(("config" "branch.search-commands.magithubPullRequestID" 19))
  magit-git-success("config" "branch.search-commands.magithubPullRequestID" 19)
  magit-set(19 "branch" "search-commands" "magithubPullRequestID")
  magithub-pull-request-checkout(...)
  funcall-interactively(magithub-pull-request-checkout ...)
  call-interactively(magithub-pull-request-checkout)
  magit-invoke-popup-action(80)
  funcall-interactively(magit-invoke-popup-action 80)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

since i never used this feature before, i assume the problem is not at my side.

help welcome!

**Comment by vermiculus** [comment]
Hm – when the error catches, what's the value of `magithub-hub-executable`? (You can use `debug-on-error` to drop yourself into the debugger and then use `e` to evaluate an expression.)

**Comment by wbolster** [comment]
```
magithub-hub-executable is a variable defined in ‘magithub-issue-tricks.el’.
Its value is "hub"
```

```
$ hub --version
git version 2.13.0
hub version 2.3.0-pre9-52-gb130068
```

(maybe a bit old, i didn't upgrade it in a while.)

looking at the exact error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp 19)
  call-process("git" nil nil nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "config" "branch.search-commands.magithubPullRequestID" 19)
```

could it be that the last `19` should've been `"19"` (as a string) instead? looks like all the other args are strings, except for that one.

**Comment by vermiculus** [comment]
Yes, that's the root, but I wonder why it's suddenly broken. It's not what I would've expected (since I recently relegated all things hub to this file).

**Comment by wbolster** [comment]
do you need any more info from me? if so, please guide me, since i do not know where to look. thanks!

**Comment by vermiculus** [comment]
Like before, what's the value of `magit-git-executable` when the error is caught? It *should* be bound to `"hub"` at that point.

**Comment by vermiculus** [comment]
(Still curious for the answer to that question 😄)

**Comment by wbolster** [comment]
it seems to be `"hub"` on each line of the backtrace where i tried `e` followed by `magithub-git-executable` (i tried a bunch).

**Comment by wbolster** [comment]
sorry, seems we both confuse some variable names.  `magithub-hub-executable` is not the same as `magit-git-executable`. there is no `magithub-git-executable` it seems.

i tried `e` followed by `magit-git-executable` on a few lines of that backtrace and it seems to be `"git"`. `magithub-hub-executable` is `"hub"`.

**Comment by vermiculus** [comment]
> `magithub-git-executable`

My bad; muscle memory. I did mean `magit-git-executable`.

I ask because, when magithub used `hub`, we let-bound `magit-git-executable` to be `magithub-hub-executable`, but from your backtrace, it appears that `git` is still being called.

**Comment by wbolster** [comment]
:green_heart:

**Comment by wbolster** [comment]
as i wrote in https://github.com/vermiculus/magithub/issues/117#issuecomment-321515403, it seems `magit-git-executable` is `"git"`; i tried on several lines of the backtrace.
