### ISSUE TITLE
Canceling a commit crashes magithub; puts it in offline mode

### ISSUE THREAD

**Issue by blaenk** [vermiculus/magithub#118]
I can consistently reproduce this. If I press `c c` to start typing out my commit message, and then say I forget something so I cancel out of it by doing `C-c C-k`, I notice that Magithub enters into offline mode and I have to toggle it to go back online.

I toggled debug on error but received no backtrace. I did see some output in my Messages buffer:

```
Running git commit -- [2 times]
Spell Checking...69%
Spell Checking completed.
Diffing changes to be committed (C-g to abort diffing) [2 times]
When done with a buffer, type C-c C-c
Type C-c C-c to finish, or C-c C-k to cancel
Commit canceled.  Message saved to ‘log-edit-comment-ring’
There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'. ... [Hit $ to see buffer *magit-process: .dots for details] [2 times]
magithub: (07:25.793) checking if the API is available
magithub: (07:25.794) making sure authinfo is unlocked
magithub: (07:25.796) cache expired; retrieving new value for api-last-checked
magithub: (07:25.796) ghub-request("GET" "/rate_limit" nil nil nil)
Contacting host: api.github.com:443
magithub: (07:25.880) consider reporting unknown error while checking api-available: (wrong-type-argument number-or-marker-p nil)
Commit canceled.  Message saved to ‘log-edit-comment-ring’
Magithub is now offline: unknown issue: (wrong-type-argument number-or-marker-p nil)
```

**Comment by blaenk** [comment]
I forgot to mention that after I notice the `GitError!` I always press `g` to refresh and clear it, which is when I notice that magithub goes offline. It doesn't show up before then (while the `GitError!` is showing).

I confirmed I'm on the latest version, well, assuming that it has already hit melpa, which can take hours.

emacs reports version `20170808.557`

**Comment by vermiculus** [comment]
I was also refreshing… very strange. I'll test in a VM tomorrow to make sure my environment isn't precluding me from seeing the bug. Thanks for the report!

**Comment by vermiculus** [comment]
I see this issue sometimes too, but I don't think it has anything to do with cancelling a commit. I think it just *happens* sometimes.

It might be something internal to `ghub` or even deeper, but I'll keep investigating here before I open up an issue there.

**Comment by vermiculus** [comment]
Just by looking at the message log, here's the offending piece of code:

```elisp
(progn
  (setq response
        (condition-case _
            (with-timeout (magithub-api-timeout (signal 'magithub-api-timeout nil))
              (ghub-get "/rate_limit"))
          (ghub-404 (ghub-get "/meta")))

        api-status
        (and response t))

  (magithub-debug-message "new value retrieved for api-last-available: %S"
                          response))
```

What is the value of `magithub-api-timeout`? If it's a number, then I think the problem is upstream in `ghub` or possibly the `json` library.

**Comment by blaenk** [comment]
I have it [set to the value 5](https://github.com/blaenk/dots/blob/ede7126fb1c4c772eefa5c1f41eec91a53b6b513/emacs/.emacs.d/inits/conf/git.el#L115), though I noticed the other day you pushed a commit that bumped it from 1 to 3, which may suffice for me, so I intend to get rid of my definition and use the new default.

**Comment by vermiculus** [comment]
Just checking in; is this still happening for you?

**Comment by blaenk** [comment]
I hope to have some time to check tomorrow.

**Comment by blaenk** [comment]
Seems like it doesn't happen anymore. 👍
