### ISSUE TITLE
Github Enterprise Integration - Detect ghub-base-url automatically

### ISSUE THREAD

**Issue by diasjorge** [vermiculus/magithub#119]
I currently work using both github.com and a enterprise edition.

Is there any way that magithub can detect based on the repository url if it should set the ghub-base-url to one that matches the repo? 

So if I see the status of a GHE project at gh.example.com it could set it to some mapped value like gh.example.com/api/v3 or a regular github project to the default url.

I could attempt to make a PR but I think there are many points in the code where you could require to know this value before making an api request, any guidance as to where to look for better in the code?

I think also the cache is not aware of the api-url and if I see the status of a GHE project but it tries to connect to github.com then it caches the 404, maybe if it knew the request goes to GHE it could add that as part of the cache key.

**Comment by vermiculus** [comment]
This *could* be done as a hook when you enter magit-status; you can set ghub-base-url local to that buffer. I agree it would be nice if it could be automagical, though -- but Enterprise-specific functionality is hard for me to test (seeing as my work doesn't use GitHub at all) 😉

**Comment by vermiculus** [comment]
I've got chrome notifications turned on for GitHub, so I get them pretty quickly 😄

and not at all! I'm glad it's turned out to be so useful to so many ❤️

**Comment by diasjorge** [comment]
I'm trying to use the magithub--parse-url function but I see in here: https://github.com/vermiculus/magithub/blob/master/magithub-core.el#L461 that the domain result is not evaluated. Can this be changed? I've tried doing eval on the result ```(cdr (assq 'domain (magithub--parse-url "git@github.example.com:example/project.git")))``` but I think it's not possible.

**Comment by diasjorge** [comment]
I managed to have some code that works to do this as you suggested.

```
  (defun magithub--url->domain (url)
    "Tries to parse a remote url into a domain"
    (cdr (assq 'domain (magithub--parse-url url))))

  (add-hook 'magit-status-mode-hook '(lambda ()
                                     (if (magithub-github-repository-p)
                                         (let* ((remote-url (magit-get "remote" (magithub-source--remote) "url"))
                                                (domain (magithub--url->domain remote-url)))
                                           (message domain)
                                           (unless (string-equal "github.com" domain)
                                             (setq-local ghub-base-url (concat "https://" domain "/api/v3")))))))
```

Would you feel this could be made part of magithub? at least the magithub--url->domain function?

I could create another package called magithub-enterprise for GHE specific features. What do you think?

**Comment by vermiculus** [comment]
Magithub should ideally support Enterprise features out-of-the-box; it seems incomplete to me without them (even though I don't personally use GHE). Can you open another PR with the code you have?

One pre-review note: look into `let-alist`.

**Comment by diasjorge** [comment]
Hi, I'll open another PR with this suggestions.
