### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by stardiviner** [vermiculus/magithub#12]
```
Symbol's value as variable is void: magithub-dispatch-key
```

**Comment by vermiculus** [comment]
What version are you on?

**Comment by stardiviner** [comment]
MELPA version: `20160918.1410`

**Comment by vermiculus** [comment]
Let me know if that works for you.

I need to start doing development on a different branch…

**Comment by stardiviner** [comment]
confirm fixed. Thanks.
