### ISSUE TITLE
Wrong `magithub-pull-request-checkout` gets loaded

### ISSUE THREAD

**Issue by ericdanan** [vermiculus/magithub#132]
The function is defined both in `magithub-pr.el` and `magithub-issue-tricks.el`, but since the latter file is loaded after the former (the latter is loaded directly whereas the former is loaded indirectly by `magithub-ci.el`, the latter definition (using `hub`) is used. I think the intended behaviour is to use the former definition instead, so perhaps the function should be removed from the latter file or renamed there.

**Comment by vermiculus** [comment]
Thanks again for the report!
