### ISSUE TITLE
Further questions about `magithub-pull-request-checkout`

### ISSUE THREAD

**Issue by ericdanan** [vermiculus/magithub#133]
Sorry for the long post and the uninformative title, I think it is not worth opening several issues but please let me know otherwise, and feel free to ignore whichever of these questions are not relevant.

1. Many PRs have as head the user's fork's `master` branch. In these cases magithub will systematically refuse to checkout the PR since there is already a local branch named `master`. Would it be possible to name the branch differently (perhaps `PR<number>` or `user/branch`...) or even to make the branch name user-customizable?

2. When the checkout succeeds, I end up in the PR branch but at the base commit, so I have to pull the PR's commits manually. Is this on purpose?

3. More generally, I wonder what are the pros and cons of creating a PR branch from the user's remote repo as opposed to directly fetching the PR ref on the `origin` remote like explained for instance [here](//endlessparentheses.com/automatically-configure-magit-to-access-github-prs.html)? I mean doing something like `(magit-fetch-refspec "origin" "+/refs/pull/<number>/head:refs/<branchname>")`. I tried this once and it seemed to do the job but I'm not sure that's a correct way to proceed.

4. Sometimes the user submitting the PR is the repository owner. In this case magithub will add a new remote `user` although it is the same as `origin`. Could this be avoided?

5. Finally, I wonder if there is a typo in the line `(magit-set (number-to-string .number) "branch" branch "magithub" "sourcePR")`. It creates a new config section `branch "<branchname>.magithub"` with an entry `sourcePR = <number>`. My impression is that the goal is instead to add an entry `"magithubSourcePR = <number>` to the `branch "<branchname>"` section, but I may be wrong.

**Comment by vermiculus** [comment]
Many issues would've been fine, but this is fine, too 😄 I recently re-implemented PR checkout, so I appreciate the feedback on it.

1. Using `user/branch` is probably best – I'll do that, thanks 😄 The situation just didn't come up in my testing.
2. It's not on purpose; I'll see if I can fix that, too.
3. Creating a new remote allows a contributor to push updates to their branch in an intuitive way. I'm not sure it would work if the branches were added as fetches to a single remote. @Malabarba, do you have any thoughts/suggestions here?
4. Can you write this up as a separate issue?
5. The new section is what was intended. Are there downsides to that approach? I can switch it up if need be, but I figured it'd be nice to have all Magithub-related stuff together.

**Comment by vermiculus** [comment]
Addendum to (3) – it looks like you can indeed have branches with a period in them (no idea why…). Do git config sections then have a limit to how much they can be organized? It might be better then to just have a `magithub` section with my own organization.

**Comment by ericdanan** [comment]
Thanks for your reply. Further comments:

1. Perhaps it would be a problem then that the local PR branch has the same name as its remote branch? In that case it could be better to prefix / replace the local branch name with the PR number.

2. Perhaps with `magit-fetch` or `magit-pull`? Personally I would only do this when creating a new PR branch and not when the PR branch already exists, but that's probably subjective.

3. I think I get your point. Do you mean that if I submit a PR to `magithub` and a collaborator of mine can push to my fork but to the `magithub` upstream repo, then the way it's done currently is the only way to allow him to push new commits to the PR? Now perhaps a drawback of this approach is that as more PRs are checked out, plenty of remotes will be added. So perhaps `magithub` could do some cleanup once in a while? For instance, advise `magit-branch-delete` so that if a PR branch is deleted and the corresponding remote is needed anymore then this remote is deleted as well.

4. OK will do.

5. Having a `magithub` section with all `magithub` settings sounds good to me.

**Comment by vermiculus** [comment]
I've removed this function in favor of magit's core handling this (#216)
