### ISSUE TITLE
quiet operation for background tasks

### ISSUE THREAD

**Issue by wbolster** [vermiculus/magithub#144]
hi, currently magithub (which is awesome) shows messages in the minibuffer, e.g. "wrote cache to ...". i find this annoying. any reason these messages cannot be removed?

**Comment by vermiculus** [comment]
That message is shown [here](https://github.com/vermiculus/magithub/blob/467ad8ccca260fca332bb0e496806005673d4175/magithub-core.el#L386):

    (magithub-debug-message "wrote cache to disk")

Looking at [the definition of `magithub-debug-message`](https://github.com/vermiculus/magithub/blob/467ad8ccca260fca332bb0e496806005673d4175/magithub-core.el#L50), output is controlled by the value of `(or magithub-debug-mode debug-on-error)`. So, one of those two is on for you.

**Comment by vermiculus** [comment]
Let me know if that doesn't work and I'll re-open this issue 😄

**Comment by wbolster** [comment]
hmmm seems i have those toggled off. will let you know if i encounter this again.
