### ISSUE TITLE
Better highlighting Unread Notifications in magit-dashboard

### ISSUE THREAD

**Issue by jgkamat** [vermiculus/magithub#151]
Continuing from #150 

The 'normal' github notification system only shows unread notifications by default (unless you ask for them). 

Here's a screenshot of the dashboard (which I think is the full dashboard now)

![2017-10-22-132649_946x943_scrot](https://user-images.githubusercontent.com/4349709/31864547-ab177bcc-b72c-11e7-9597-f616c6de6aab.png)

This is pretty unusable, since I've already seen all the notifications on the screen, and the notifications go down for a long while. A easy improvement for UX (I think) is collapsing the headers by default:

![2017-10-22-131913_536x512_scrot](https://user-images.githubusercontent.com/4349709/31864455-aa302976-b72b-11e7-954e-e80fdc40b375.png).

However, this is still pretty painful (trying to find unread notifications) After scrolling down a long while, I came up with some of my unreads:

![2017-10-22-133004_974x881_scrot](https://user-images.githubusercontent.com/4349709/31864559-20714f74-b72d-11e7-9a65-f3b4c702ee71.png)

Another easy fix for this is to sort by newest first. I don't particularly like this because it encourages you to leave notifications un-attended for a while, but it is an easy fix.

A better fix (IMO) would be:

- Show only unread notifications by default (speed up queries to github, only show needed information)
- Make unread notifications a magit popup option (or a variable)

OR:

- Create two drawers, one for unread notifications and one for read ones
- The read drawer should be closed by default, and the unread one should be closed for details, open for notifications.

I like the first option more, since it would make opening it faster.

What are your thoughts on the issue? I'm not too familiar with the github API, so I'm not sure if getting only unread notifications is possible.

**Comment by vermiculus** [comment]
Only getting unread notifications is certainly possible and I can easily make that the behavior. What surprises me is the sheer number of notifications you have – I can never get more than 15 or so (read or unread) to show up, so I never experiences this usability issue.

Aside, only unread notifications should be expanded by default. Can you kill the buffer and reopen the dashboard? Are they all still expanded? That shouldn't be the case.

**Comment by jgkamat** [comment]
>  What surprises me is the sheer number of notifications you have – I can never get more than 15 or so

I'm not sure what consitutes as an 'unread' notification by the github API. I have had a lot more unread notifications in the past, maybe there's some sort of time cutoff. I watch a lot of repos :P 

> Aside, only unread notifications should be expanded by default. Can you kill the buffer and reopen the dashboard? Are they all still expanded? That shouldn't be the case.

They are definetly still expanded for me, is there any debug information I could provide that would help with that? :)

**Comment by stardiviner** [comment]
Why my command `magithub-dashboard` is not available after upgrade package `magithub`?

**Comment by jgkamat** [comment]
@stardiviner try `(require 'magit-dash)`.

Maybe an autoload on the function could be added to make it easier

**Comment by stardiviner** [comment]
@vermiculus Can you add autoload cookie ahead of function?

**Comment by vermiculus** [comment]
@stardiviner it's already there

**Comment by jgkamat** [comment]
magithub now hides read notifications by default, so I'm closing this. Feel free to reopen if this is still being worked on :)
