### ISSUE TITLE
Magithub can query API in offline mode if the repository is a fork

### ISSUE THREAD

**Issue by jgkamat** [vermiculus/magithub#154]
If

`(magit-get-push-remote (magit-get-current-branch))` 

is non-nil, magithub will query the github api in offline mode, leading to a crash when offline (and bypassing cache).

The offending line of code is [here](https://github.com/vermiculus/magithub/blob/master/magithub-ci.el#L84), and on 'normal repos' without pushdefault set, the code never runs [due to this check](https://github.com/vermiculus/magithub/blob/master/magithub-ci.el#L82). 

To reproduce, set `remote.pushdefault=origin` or similar in your repo gitconfig (or through magit via `b p` or `b M-p`), and then run `(magithub-ci-status--get-default-ref)`

I was able to find exactly where this happens, but I have no idea how to fix it properly, hence this issue. 

Let me know if you can't reproduce, and I'll send you a backtrace, but I think I got it pinned down fairly well. Also, if you do trigger a backtrace with this error, it puts magit in a weird state (all drawers default to open and colors are broken) and I have to restart emacs.

**Comment by vermiculus** [comment]
Quick fix for you right now – set `branch.yourbranch.magithub.sourcePR` to the pull request number of that branch. An API request is only made to 'guess' at the PR if that property isn't there :-)

I'll look into making this heuristic a little better (at least insofar as respecting offline mode).

**Comment by vermiculus** [comment]
I'm in the middle of staging/committing a few core caching changes (which I want to review thoroughly), but try these definitions for a spin:

```elisp
(defun magithub-pull-request-branch->pr--ghub (branch)
  "This is a hueristic; it's not 100% accurate.
It may fail if the fork has multiple branches named BRANCH."
  (let ((repo (magithub-repo-from-remote (magit-get-push-remote branch))))
    (when (alist-get 'fork repo)
      (let* ((guess-head (format "%s:%s" (magit-get-push-remote branch) branch))
             (prs (ghubp-get-repos-owner-repo-pulls (magithub-repo) :head guess-head)))
        (pcase (length prs)
          (0)    ; this branch does not seem to correspond to any PR
          (1 (magit-set (number-to-string (alist-get 'number (car prs)))
                        "branch" branch "magithub" "sourcePR")
             (car prs))
          (_ ;; todo: currently unhandled
           (signal 'magithub-error-ambiguous-branch
                   (list :prs prs
                         :guess-head guess-head
                         :repo-from-remote (alist-get 'full_name repo)
                         :source-repo (alist-get 'full_name (magithub-repo))))))))))

(defun magithub-pull-request-branch->pr--gitconfig (branch)
  "Gets a pull request object from branch.BRANCH.magithub.sourcePR"
  (when-let ((source (magit-get "branch" branch "magithub" "sourcePR")))
    (magithub-pull-request (magithub-repo) (string-to-number source))))

(defun magithub-ci-status--get-default-ref (&optional branch)
  "The ref to use for CI status based on BRANCH.

Handles cases where the local branch's name is different than its
remote counterpart."
  (setq branch (or branch (magit-get-current-branch)))
  (if-let ((pull-request
            (or (magithub-pull-request-branch->pr--gitconfig branch)
                (and (not (magithub-offline-p))  ;;;;;;;;;;;; note
                     (with-demoted-errors "Error: %S"
                       (magithub-pull-request-branch->pr--ghub branch))))))
      (let-alist pull-request .head.sha)
    (when-let ((push-branch (magit-get-push-branch branch)))
      (cdr (magit-split-branch-name push-branch)))))
```

**Comment by jgkamat** [comment]
Yup, this patch works great for me, nice! I guess this issue can be closed now if you want :)

**Comment by vermiculus** [comment]
It'll be closed once that commit moves to master :-) Thanks for letting me know!
