### ISSUE TITLE
No GitHub repository to visit

### ISSUE THREAD

**Issue by jiacai2050** [vermiculus/magithub#155]
Maybe a silly question, but after I install magithub, and configure `(magithub-feature-autoinject t)` directly without using 'use-package', it always says this error msg `No GitHub repository to visit` when I execute some magithub command in my github repo.

```
(defun magithub-browse ()
  "Open the repository in your browser."
  (interactive)
  (unless (magithub-github-repository-p)
    (user-error "Not a GitHub repository"))
  (let-alist (magithub-repo)
    (unless (stringp .html_url)
      (user-error "No GitHub repository to visit"))
    (browse-url .html_url)))
```
I have checked the the source code, but have no ideas where `.html_url` came from.
Is there anything I'm missing? Thanks in advance.

- magithub-20171021.1302

**Comment by vermiculus** [comment]
Clearly the function is getting defined, so I doubt that's an issue.

The `.html_url` is being let-bound by `let-alist` to access (essentially) `(alist-get 'html_url (magithub-repo))`. When you evaluate `(magithub-repo)` in your magit-status buffer, what's the return value?

**Comment by jiacai2050** [comment]
nil

**Comment by vermiculus** [comment]
What's the URL you use for the github remote? I suspect we just don't handle its format yet in `magithub--repo-parse-url`. (You can instrument that function to verify this.)

**Comment by jiacai2050** [comment]
Sorry for my delay.

I reinstall magithub, and everything works fine.

**Comment by vermiculus** [comment]
Happy to hear it 👍

**Comment by jiacai2050** [comment]
Thanks for your attention.  Magithub is really useful for me. ❤️
