### ISSUE TITLE
How to pull request?

### ISSUE THREAD

**Issue by lpvm** [vermiculus/magithub#167]
For sure this is something on my fault...
From github, did a git clone in terminal.
After changing a file in emacs, commited and did a push to the github cloned repository.
But how can I do a pull request now?  Can't find the way.

Just to exemplify.
In a text file, `SPC + g + s` for status
Then when I press `H` in the Magit window, the cursor goes to the top as the Vim command.

**Comment by vermiculus** [comment]
Sorry, I really don't know enough about spacemacs to help; I've never used it. 

Perhaps folks on that repo can help? `H` is the dispatch key we use; I don't know if spacemacs modifies its placement.

**Comment by vermiculus** [comment]
Did you ask spacemacs folks about this?

**Comment by lpvm** [comment]
It's solved.  There's a `github` layer, but had to do as shown in http://jr0cket.co.uk/2017/02/spacemacs-using-magit-with-github.html.  Thank you @vermiculus
