### ISSUE TITLE
magit-buffer-lock-functions not defined?

### ISSUE THREAD

**Issue by jwiegley** [vermiculus/magithub#171]
`magithub-issue-view` seems to require `magit-buffer-lock-functions`, but this is not defined in the current version of magit (2.11.0).

**Comment by vermiculus** [comment]
magit/magit#3191 is merged, but is it released? (I'm relegated to my phone right now, but that's the most likely cause here.)

**Comment by vermiculus** [comment]
Doesn't look like it's released -- I assume you're not tracking HEAD via melpa or some other means?

**Comment by jwiegley** [comment]
I am tracking head of magithub, just not head of magit.

**Comment by gonewest818** [comment]
Should this issue be reopened?  Arguably the [package dependencies](https://github.com/vermiculus/magithub/blob/master/magithub.el#L8) should be updated to `(magit "2.12")` upon the next release of magit.

**Comment by vermiculus** [comment]
When 2.12 is released, I'll be sure to update the dependency 🙂

As a related discussion, I wonder if it's possible to install the specific package versions specified in the header. An environment variable could be set up in the CI testing matrix to test both 'normal' and 'stable' builds.

**Comment by gonewest818** [comment]
I think the problem is that upstream packkage repos don't keep prior versions of anything, which is the reason Spacemacs seems to be keeping their own "pinned" dependencies in a github repo: https://github.com/syl20bnr/spacelpa

**Comment by vermiculus** [comment]
True, but the package repositories (like MELPA) know where to find the code to build the package. If we can access that information, then all that's needed is some cleverness with `package-desc-version` and various checkout methods.

This would only work for packages under some VCS, though.

**Comment by gonewest818** [comment]
fwiw, there's a ticket open in MELPA, and it seems Steve is open to the idea but limited in time and resources. https://github.com/melpa/melpa/issues/4712
