### ISSUE TITLE
"Token not found" error

### ISSUE THREAD

**Issue by kvolkovich-sc** [vermiculus/magithub#172]
(Its a duplicate of https://github.com/magit/ghub/issues/36)

I install "magithub" from "Melpa"

It depends on "ghub". When I try to auth, it fails with error "Token not found".  `ghub--auth-source-get` always returns `nil`.

`hub browse`, then input login, pass works correctly.

I solved auth problem by replacing content of **ghub.el** dependency locally to https://raw.githubusercontent.com/magit/ghub/c74101ca6235a20ec428ed223ce060a61db26148/ghub.el.

P.S. Do you know, is there any to set specific dependency version (I am not a pro in emacs) to avoid these types of confusing errors?)

**Comment by vermiculus** [comment]
I saw the previous issue you posted; why create this duplicate?

**Comment by vermiculus** [comment]
Generally you can use melpa-stable, but it's often difficult to manage such streams (especially for software packages like ghub/magithub that are still in their infancy).
