### ISSUE TITLE
Some things I've noticed

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#175]
- `magithub.org` needs updating.
   - Most importantly `(ghub-get "/user" nil :auth 'magithub)`.
   - There are also some Org syntax issues.
   - A toc would be nice, I find myself scrolling up and down a lot while writing this.
   - The information about `hub` should probably not come so earlier. Just a few days ago a user reported that they installed `hub` and things didn't work afterwards. By not putting information about `hub` before that about `ghub` that could be avoided. (But I would move it even further out of sight.)
- Did you try https://github.com/magit/magit/pull/3134 yet? (I haven't tried `magithub` for a while. As you can see I am doing that now :wink: )
  - Ignore the stubs added in the last two commits.
  - Some edge-cases are not covered but otherwise it is quite nice.
  - I will resume working on this again shortly.
  - That should cover the things that `magithub` still needs `hub` for. Further reason to move information about that out of sight.
- `Magithub: OFFLINE; use C-p g to refresh GitHub content or H O to go back online...`
  - I want that line for the `OFFLINE`, but the rest I would like to turn of using an option or something.
  - Actually, once the state is displayed in the popup (see below) I don't need this at all.
- The order in the popup doesn't make much sense to me. Does it assume a certain number of columns? Then you should enforce it.
- `H [eaten by Github] Toggle Magithub-Status integration` Does that locally set a git variable? Then you should probably display the value in the popup.
- `g	Refresh this section only` You shouldn't mess with that. `g` is supposed to always refresh all of the current buffer.
- `H c Create` Create what?
- `H i Issues` I expected a list of issues or something, not creating a new issue.
- `... Toggle ...` The current state should be shown.
- When the push-remote is configured but the branch by the push-target branch doesn't exist yet:

```
  error("Invalid branch name %s" "tarsius/master")
  magit-split-branch-name("tarsius/master")
  magithub-ci-status--get-default-ref()
  magithub-insert-ci-status-header()
  magithub-maybe-insert-ci-status-header()
```
- I didn't have the `magithub` token yet and the setup process wasn't quite what I expected (pressing `C-u g`):
  - `Refresh GitHub data? (y or n)` So far so good.
  - `GitHub doesn't seem to [be] responding, are you sure? (y or n)` No, I am not sure that Magithub actually tried talking to Github but I suspect I have to answer `y`.
  -  ... things are being fetched
  - Echo area says `(magithub): buffer data refreshed`
  - Typing reveals that Emacs is actually trying to read in the minibuffer. Making sure I still provide `tarsius` as input at `Username [for https://tarsius@api.github.com]: ` (That prompt is a bit unfortunate as mentioned in the `ghub` manual. I will look into doing something about that again, but since it is actually `url` asking that, that could be hard.
  - This works, but not if the token already exists on Github but not locally. But that's probably a `ghub` bug - investigating.

**Comment by tarsius** [comment]
>> This works, but not if the token already exists on Github but not locally.

> I suspect that's what magit/ghub@58e4a46 was about? 

That and there are also two bugs in `auth-source` the nicely complement each other.

1. New entries are added at the very beginning of the buffer, even when it begins with a comment such as `# -*- epa-file-encrypt-to: ("jonas@bernoul.li") -*-`
2. If an entry is right before a comment line, then it fails to parse the secret.

I should be able to fix (2) using an advice.

**Comment by tarsius** [comment]
> CI status bug. Can you submit a separate issue? I want to fix this, but it'll get lost in here.

There must be a misunderstanding - not surprising, I was just writing stuff down. I didn't say anything about CI I think. What part are you referring too?

**Comment by tarsius** [comment]
> Thanks again for all the great feedback; I really appreciate it!

Same to you!

**Comment by tarsius** [comment]
And sorry for opening a monster issue. Feel free to split this up and ping me in any new issues your create to replace this.

**Comment by vermiculus** [comment]
For the CI status bug, I'm referring to this chunk:
> - When the push-remote is configured but the branch by the push-target branch doesn't exist yet:
>
> ```
>   error("Invalid branch name %s" "tarsius/master")
>   magit-split-branch-name("tarsius/master")
>   magithub-ci-status--get-default-ref()
>   magithub-insert-ci-status-header()
>   magithub-maybe-insert-ci-status-header()
> ```

I've created an issue for this.

No worries about opening a monster issue :)

Do you have any pointers about the popup stuff?  Looking at the manual, it looks like these keywords will be useful:
- `:variables`
- `:max-action-columns`

**Comment by tarsius** [comment]
> For the CI status bug, I'm referring to this chunk:

Just came back to say I realized that too now. Well, it's not really a bug in the CI code, I suspect some other section might trigger the same issue if this one didn't do so first. Or not. And a `when-let*` should do the trick.

> Do you have any pointers about the popup stuff? Looking at the manual, it looks like these keywords will be useful:

> :variables
> :max-action-columns

Yes, those are the relevant variables.

Unfortunately, as the name suggests, you can only specify how many columns to use at most.

And `:variables` is what you should use for the state information. But that was designed with Git variables in mind, isn't documented, and has not been abstracted enough yet. So this will likely take quite a bit of boilerplate code to implement. Look at `magit-notes-popup` for an example.

**Comment by tarsius** [comment]
Such details aside, the experience is much smoother now than the last time I tried `magithub`. Congratulations!

**Comment by vermiculus** [comment]
Having opened the issues above (I think that covers everything you brought up), I'm closing this issue.

Thanks again!
