### ISSUE TITLE
magithub can't read authinfo token correctly

### ISSUE THREAD

**Issue by stardiviner** [vermiculus/magithub#178]
I have file `~/.authinfo.gpg` which has content like this:
```
# -*- epa-file-encrypt-to: ("stardiviner") -*-
machine api.github.com login stardiviner password <token>
```
But magithub keep raise prompt and warning:
```
auth-source-search: found 0 results (max 1) matching (:max 1 :host "api.github.com" :user "stardiviner^magithub")
Invalid face reference: PDFView [14 times]
Such a Github API token is not available:

  Host:    api.github.com
  User:    stardiviner
  Package: magithub

  Scopes requested in `magithub-github-token-scopes':
    repo
    user
    notifications
  Store locally according to `auth-sources':
    ("~/.authinfo" "~/.authinfo.gpg" "~/.netrc")
  Store on Github as:
    "Emacs package magithub @ dark"

WARNING: If you have enabled two-factor authentication then
         you have to abort and create the token manually.

If in doubt, then abort and view the documentation first.

Otherwise confirm and then provide your Github username and
password at the next two prompts.  Depending on the backend
you might have to provide a passphrase and confirm that you
really want to save the token.

Create and store such a token? (y or n) n
```

**Comment by vermiculus** [comment]
This is a ghub thing, but basically you can either remove the line and let ghub create a new token for you or you can add `^magithub` to your username, restart emacs (or `M-x auth-source-forget-all-cached`), and try again.

**Comment by humitos** [comment]
I recently had this same problem. My file `~/.authinfo`

    host api.github.com user humitos^magithub password <token-2-factor-auth> port https

Hope it helps.

**Comment by vermiculus** [comment]
Why is `port` specified? (I'm not sure it would make a difference anyway, but…) I don't have that for my config.

**Comment by humitos** [comment]
Probably not a difference. It's on the emacs manual at https://www.gnu.org/software/emacs/manual/html_node/auth/Help-for-users.html#Help-for-users

I think it just adds another layer as filter. You just could use 

    password <token>

and it should work, but **it's not recommended**

**Comment by vermiculus** [comment]
Huh, TIL. To clarify, are you still having trouble authenticating?

**Comment by humitos** [comment]
Nope. I'm loving magithub back again :)

**Comment by humitos** [comment]
Ups, sorry. I wasn't clear in my first comment.

I ment that I **solved my auth problem** with that configuration. Sorry about the confusion.

**Comment by stardiviner** [comment]
After adding ^magithub. It works. But after upgrade, it will prompt to create a new token again.
I also tried @humitos mentioned method. not work too.
Do I need to re-generate token after enable two-factor auth or toggle a new two factor auth?

**Comment by vermiculus** [comment]
I'm not sure how ghub handles two-factor authentication. I'd refer you to [the manual](https://github.com/magit/ghub/blob/master/ghub.org), but I'm pretty sure if you enable 2FA, you need to generate a token and configure it manually. If the manual can be made more clear on this point, I'd direct that feedback to an issue on [magit/ghub](https://github.com/magit/ghub), where authentication is actually handled.
