### ISSUE TITLE
Our own GitHub-Message mode

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#18]
We're using `git-commit` mode right now, but this is probably inappropriate.  We should be deriving from `markdown-mode` (or similar) -- maybe with support for checklists like this?  Is there a 'GitHub-Flavored Markdown mode'?  These are the questions that keep me up at night.

Could derive from `org-mode`, too, but that might introduce more problems than it's worth.
- [ ] allow referencing pulls/issues with `#` with completion
- [ ] collapse (i.e. overlay) full 40-char commit hashes into something more readable

**Comment by vermiculus** [comment]
Probably could also fix #15

**Comment by xendk** [comment]
markdown-mode https://melpa.org/#/markdown-mode includes an gfm-mode, I'd suggest that.

**Comment by vermiculus** [comment]
@xendk Yep, that's what I'm planning on using, but there are still a few bugs that I'd like fixed before I'm ready to release this.

Cf jrblevin/markdown-mode#169
