### ISSUE TITLE
[Question/feature request] Is there any way to use https for fork remotes?

### ISSUE THREAD

**Issue by dieggsy** [vermiculus/magithub#180]
As the title says, it'd be nice to have an option for what protocol is used for fork remotes.

**Comment by vermiculus** [comment]
You should be able to use [`magithub-preferred-remote-method`](https://github.com/vermiculus/magithub/blob/6e35d5a136a62358187e85bb1fa66b4a4d37b03a/magithub-core.el#L914).

Perhaps we should consider making it a `defcustom`.
