### ISSUE TITLE
Feature Request: Open PR in the Browser and/or add to kill ring after PR is submitted

### ISSUE THREAD

**Issue by stevenmccord** [vermiculus/magithub#183]
# Feature Requests

Github layer in spacemacs used to have this feature where you can submit a PR and it would auto open in browser (this is helpful if you use a plugin like Zenhub where you need to add more fields to the ticket) or at the very least add to the kill ring so that you could immediately go to it.

**Comment by vermiculus** [comment]
This is related to #177 -- it should be doing this, but we're erroring out too quickly. If you see the pull request anywhere in emacs though, `w` (as in **www**.domain.com) should open the PR in a browser.

**Comment by vermiculus** [comment]
Should be addressed by above PR.
