### ISSUE TITLE
Don't unfill code blocks

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#19]
When fenced or indented code blocks are added, the unfill logic forces it all onto one line.  This is _really_ gross.

Probably related to #18.

Caused by d73b18b64fb89a86f11422e30082cadedabb76a4.

**Comment by vermiculus** [comment]
related jrblevin/markdown-mode#169

**Comment by MaikuMori** [comment]
Same happens with lists:

```
Text like this will have all the list items in one line:

 - ItemA
 - ItemB
 - ItemC
```
