### ISSUE TITLE
void-function ht\?

### ISSUE THREAD

**Issue by jscheid** [vermiculus/magithub#193]
Hi, when running `M-x magit-gh-pulls-reload` I'm getting the following error:

```
Debugger entered--Lisp error: (void-function ht\?)
  ht\?(:json-false)
  #[(obj blob) "\204\301\207\302!\203\303\207;\203\304\207\247\203\305\207<\203#\306\207\307!\205*\310\207" [blob nil booleanp bool string number list ht\? hash] 2]([eieio-class-tag--marshal-driver-alist unbound unbound] :json-false)
```

The whole backtrace is 8MB and might contain sensitive data (this is with a customer's private repository) so I'd rather not post it here. I hope that from the above you can see what's going on? Let me know if not and I'll try to dig deeper.

**Comment by jscheid** [comment]
Sorry, wrong project! I got confused because I just installed `magithub` but forgot that I had installed `magit-gh-pulls` a while back.

**Comment by vermiculus** [comment]
I was just about to say 👍
