### ISSUE TITLE
can't submit PR

### ISSUE THREAD

**Issue by aspiers** [vermiculus/magithub#195]
Hi, thanks for this totally awesome project which I only recently discovered.  I just tried to submit a PR via `H p` for the first time, and noticed two issues.

Firstly the first `"Fork's remote (this is you!)"` prompt is missing whitespace after the prompt, and has excess whitespace in between the git remote name and the corresponding repository name on GitHub.  However this is just cosmetic and not a big problem, whereas the second problem is a show-stopper:

The second and third prompts for the `"Head branch"` and `"Base branch"` do not offer the correct branches.  I've looked into this and AFAICS it appears to be due to an incorrect assumption either that there is only one remote, or that the first remote returned by `magithub-repo-remotes-for-repo` is always relevant to the creation of the PR.  Neither of these are true in my case (and in many other cases, I expect).  On many repos I have at least 6 remotes, and the first one in this list is rarely relevant to this process.

This assumption is due to calling `car` on the list of remotes, to take the first one available and assign it to `this-remote` and `base-remote`:

- https://github.com/vermiculus/magithub/blob/fce4e620fda77f3a7109f7bef3b927e173c9d582/magithub-issue-post.el#L205
- https://github.com/vermiculus/magithub/blob/fce4e620fda77f3a7109f7bef3b927e173c9d582/magithub-issue-post.el#L207

These two `car` calls originate from https://github.com/vermiculus/magithub/commit/b31235b865ae2b4cfaf8b8bea7724cf23c58380f but I couldn't figure out the logic behind the change.  Thanks for any light you can shed!

**Comment by xuchunyang** [comment]
I am also not be able to submit PR.

![screen shot 2018-01-13 at 6 25 23 pm](https://user-images.githubusercontent.com/4550353/34905216-24be7afe-f88f-11e7-8c81-2f6f17835085.png)

then when I press the submit button, I get

> user-error: This pull request already exists!

in the end I have to submit this PR through github web interface.

**Comment by aspiers** [comment]
@xuchunyang That's a totally different problem to mine; please can you submit a separate issue for that?

**Comment by xuchunyang** [comment]
OK, I will try to do that when I have opportunity to submit PR and encounter the issue again.

**Comment by xuchunyang** [comment]
@aspiers I just make a PR successfully after I learn that I must push my local branch to remote in advance. Though the error message ("This pull request already exists!") is misleading. Sorry for the noice.

**Comment by aspiers** [comment]
@xuchunyang Yes you are right, if that is the case then the error message is misleading, and it's still worth filing an issue to track that to resolution. Thanks!

**Comment by xuchunyang** [comment]
@aspiers I will try to fill an issue next time when I encounter the problem, thanks for reminding.

**Comment by xuchunyang** [comment]
@aspiers I have filed an issue on it, see #202.

**Comment by vermiculus** [comment]
Sorry for my silence; I've been a busy bee working on the above PR (which could resolve your issue, @xuchunyang).

It does not however change the behavior of choosing the first remote for the repo. My assumption is based on the idea that there is no reason (that I know of) to have multiple remotes pointing to the same URL. What does `(magithub-repo-remotes-for-repo (magithub-read-repo "Fork's remote (this is you!)"))` return for you? If it does indeed describe more than one remote, can you give more details on your workflow?

**Comment by xuchunyang** [comment]
@vermiculus I have not tried your PR. I am talking about the current master. It looks like after I choose my remote ("xuchunyang" in following example), it asks me to choose a Head branch 

![screen shot 2018-01-18 at 2 57 41 pm](https://user-images.githubusercontent.com/4550353/35084739-6524cd6c-fc60-11e7-91f5-f64d0d645f79.png)

however, I can still be able to choose "foobar" branch which is not pushed on remote yet, then in the very end it reports "user-error: This pull request already exists!". This is just my guess, I am not familiar with the code.

**Comment by aspiers** [comment]
On 18 Jan 2018 04:22, "Sean Allred" <notifications@github.com> wrote:

It does not however change the behavior of choosing the first remote for
the repo. My assumption is based on the idea that there is no reason (that
I know of) to have multiple remotes pointing to the same URL.

But they point at different URLs, not the same one.

What does(magithub-repo-remotes-for-repo (magithub-read-repo "Fork's remote
(this is you!)")) return for you? If it does indeed describe more than one
remote, can you give more details on your workflow?

**Comment by aspiers** [comment]
On 18 Jan 2018 04:22, "Sean Allred" <notifications@github.com> wrote:
> It does not however change the behavior of choosing the first remote for
> the repo. My assumption is based on the idea that there is no reason (that
> I know of) to have multiple remotes pointing to the same URL.

But they point at different URLs, not the same one.

> What does `(magithub-repo-remotes-for-repo (magithub-read-repo "Fork's
> remote (this is you!)"))` return for you? If it does indeed describe
> more than one remote, can you give more details on your workflow?

Ah I see what you are getting at - so the issue is actually earlier than I realised, with this bit of the code which acts on the remote selected by the first prompt.  You are saying that this code should only return one remote, whereas for me it returns a list of all my remotes.  So I think there must be an issue with the `-filter` call.  There is nothing special about my workflow.  I typically have:

*   a remote called `origin` for the upstream
*   a remote called `github` for my github fork
*   a remote for each of my personal machines (laptop, workstation etc.)
    so I can share code across my machines

**Comment by vermiculus** [comment]
> Ah I see what you are getting at - so the issue is actually earlier than I realised, with this bit of the code which acts on the remote selected by the first prompt.  You are saying that this code should only return one remote, whereas for me it returns a list of all my remotes.  So I think there must be an issue with the `-filter` call.  There is nothing special about my workflow.  I typically have:
>
> *   a remote called `origin` for the upstream
> *   a remote called `github` for my github fork
> *   a remote for each of my personal machines (laptop, workstation etc.) so I can share code across my machines

Can you evaluate a few forms in the directory you're having problems with?  I'm hoping I can mock up a test where I can see the problem on my end.

``` emacs-lisp
(let ((remotes (magithub-repo-remotes)))
  (vector
   remotes
   (magithub-repo-remotes-for-repo (magithub-repo))
   (mapcar #'magithub-repo-from-remote
           (mapcar #'car remotes))))
```

Also, if you're comfortable with it, I believe copying in your `.git/config` could accomplish the same goal.  I'm not sure, though.

**Comment by aspiers** [comment]
[Here](https://gist.githubusercontent.com/aspiers/d174ab912c7586083ae850cac37c8364/raw/82c5cf66a5aca7b71c070493d3864ea10c558207/gistfile1.txt)'s the result.

**Comment by vermiculus** [comment]
Looks like it's probably an issue with `magithub-repo-from-remote--sparse`, actually. What's the value of `remote.REMOTE.url` where REMOTE is one of the remotes that does *not* point to a GitHub repo?

**Comment by vermiculus** [comment]
Are you still having this issue?

**Comment by justinweiss** [comment]
Hey, I seem to be running into this issue -- I have two remotes, `heroku` and `origin`, and it's only showing the branches I've pushed to heroku, even after I select `origin`. It looks like, after running 

```
(let ((remotes (magithub-repo-remotes)))
  (vector
   remotes
   (magithub-repo-remotes-for-repo (magithub-repo))
   (mapcar #'magithub-repo-from-remote
           (mapcar #'car remotes))))
```

that all of the remotes are pointing at the github URL, even though they point to the correct heroku url in my `.git/config`.

**Comment by vermiculus** [comment]
What do your remotes look like in your `.git/config`?

**Comment by justinweiss** [comment]
```
[remote "origin"]
        url = git@github.com:aha-app/slate-test.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[remote "heroku"]
        url = https://git.heroku.com/heroku-app-name.git
        fetch = +refs/heads/*:refs/remotes/heroku/*
```

**Comment by vermiculus** [comment]
@aspiers @justinweiss Can you both confirm if #285 fixed this for you? Otherwise I can reopen this issue.

**Comment by aspiers** [comment]
Thanks a lot! Really busy but will try to test soon - if you don't hear from me then assume it's fixed :-)
