### ISSUE TITLE
CI Status in the status buffer

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#20]
This would be nice to have :smile: I wonder if its caching structure should be different though.  Might have to rework it a little.

**Comment by vermiculus** [comment]
Preview:

<img width="340" alt="screen shot 2016-09-21 at 12 56 51 am" src="https://cloud.githubusercontent.com/assets/2082195/18699334/5f319554-7f96-11e6-9150-64c16d5d7e29.png">

**Comment by stardiviner** [comment]
This is great. I like this.

**Comment by vermiculus** [comment]
@stardiviner FYI :)

**Comment by stardiviner** [comment]
This should CI status should not run if repository does not have CI.

**Comment by vermiculus** [comment]
Can you open as a new issue?
