### ISSUE TITLE
Misleading error message "This pull request already exists!"

### ISSUE THREAD

**Issue by xuchunyang** [vermiculus/magithub#202]
I am creating a pull request then click `[Submit new pull request]` button, I get

> user-error: This pull request already exists!

However, I am sure the pull request doesn't exist after checking github. The real cause is I don't push the local branch to the remote in advance, after I have done that, I can create the pull request successfully.

**Comment by vermiculus** [comment]
Fixed in #204, thanks for the report!

I find myself in the awkward position of needing to regularly contribute to *other* projects to properly maintain *this* one :smile:  There's no better vetting than real-world use.

**Comment by vermiculus** [comment]
204 is now merged.
