### ISSUE TITLE
When reporting an issue I get an error in `magithub-edit-delete-draft`

### ISSUE THREAD

**Issue by hexmode** [vermiculus/magithub#248]
emacs-version: "27.0.50"

The error indicates `buffer-file-name` is not defined.

Backtrace coming shortly, I hope.

**Comment by hexmode** [comment]
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  (if (file-exists-p buffer-file-name) (progn (delete-file buffer-file-name magit-delete-by-moving-to-trash)))
  magithub-edit-delete-draft()
  magithub-issue-post-submit()
  funcall-interactively(magithub-issue-post-submit)
  call-interactively(magithub-issue-post-submit)
  magithub-edit--done(magithub-issue-post-submit)
  magithub-edit-submit()
  funcall-interactively(magithub-edit-submit)
  call-interactively(magithub-edit-submit nil nil)
  command-execute(magithub-edit-submit)

**Comment by vermiculus** [comment]
Ah, I'd been testing `magithub-edit-cancel`.
