### ISSUE TITLE
magithub-issue--process-line: Search failed: "]"

### ISSUE THREAD

**Issue by IvanMalison** [vermiculus/magithub#26]
I always get this message whenever I enter magit-status

**Comment by vermiculus** [comment]
Can you please provide the output when `debug-on-error` is set? (`M-x toggle-debug-on-error`)

**Comment by vermiculus** [comment]
And what version of `hub` do you have?

**Comment by IvanMalison** [comment]
git version 2.10.0
hub version 2.2.5

**Comment by vermiculus** [comment]
This is not the same error.

Regardless, is this repeatable with an up-to-date Magithub? If so, what does `(magithub-ci-status)` return?

**Comment by vermiculus** [comment]
@IvanMalison Do you continue to see this issue? I've not been able to reproduce.

**Comment by vermiculus** [comment]
I'll close this for now; I've not seen the issue and we've not heard a response from @IvanMalison.
