### ISSUE TITLE
optionally make refresh hook into magit-refresh

### ISSUE THREAD

**Issue by wbolster** [vermiculus/magithub#27]
magithub is wonderful.

but.

i really do not like how it does network requests everytime i `(magit-refresh)` the magit status window, which i do quite a lot, since the github requests are slowing things down significantly.

it would be great if magithub:

* had a `defcustom` (defaulting to `t` to keep the current behaviour) to disable the automatic sync in `magit-refresh`

* offered an explicit `magithub-refresh` command, which would also be available from the magithub submenu in the magit popup window.

**Comment by vermiculus** [comment]
I'll look into this – I've been having the same qualms with it.

Note that you can be sure to submit issues to the right repo with `H &`.

**Comment by vermiculus** [comment]
In the meantime, you can customize (well, set) `magithub-cache-refresh-seconds` to a value of your choosing.

**Comment by vermiculus** [comment]
Related #22

**Comment by vermiculus** [comment]
@wbolster How does the above work for you?

**Comment by wbolster** [comment]
much better, thanks.

but i would still like a way to not have magithub do ANY network requests at all. i'm sometimes offline or on very crappy networks (metered mobile tethering) and want to use magit without doing any network access.

**Comment by vermiculus** [comment]
@wbolster How does the above work for you? 😄

**Comment by wbolster** [comment]
much better, thanks. again.

am i right in understanding that this is persistent per repo?

**Comment by wbolster** [comment]
may i ask why you think an explicit "fetch github data" action, just like "fetch" (or pull), is a worse solution than a per-repo toggle?

**Comment by vermiculus** [comment]
> am i right in understanding that this is persistent per repo?

Yep! It uses `git config` variables.



> may i ask why you think an explicit "fetch github data" action, just like "fetch" (or pull), is a worse solution than a per-repo toggle?

Frankly I didn't consider a 'fetch github data' option -- I'm often working in multiple projects at once (mostly submodules), so fetching new data every time I switch would be pretty inconvenient. Even "fetch" is repo-specific -- you fetch commits *for a repo*, so you fetch issues *for a repo*.

(But really, it just comes down to 'I didn't consider that option' -- I wasn't consciously thinking it was worse :shrug:)

**Comment by wbolster** [comment]
ah, i thought i implied an explicit fetch step in my original report; but i guess i wasn't express myself clearly since i used the word 'refresh'.
