### ISSUE TITLE
Refreshing GitHub data shows duplicate magit windows

### ISSUE THREAD

**Issue by rosston** [vermiculus/magithub#29]
When I'm in a GitHub repository that has any issues or PRs, refreshing GitHub data with magithub causes another window to be opened. This _only_ happens when the repo has at least one issue or PR. It consistently happens when explicitly refreshing magithub and occasionally happens when refreshing magit in general.

Example (the section is not expanded, but there is one issue):

![magithub](https://cloud.githubusercontent.com/assets/108518/18858095/9d5914d8-8437-11e6-9cc0-c4335002378a.gif)

**Comment by rosston** [comment]
Just realized I forgot to list the version. This issue is with version 20160925.2052 on MELPA.

**Comment by vermiculus** [comment]
Hey @tarsius – any idea why this might be happening? Here's the definition for `magithub-refresh`:

```elisp
(defun magithub-refresh ()
  "Refresh all GitHub data."
  (interactive)
  (setq magithub-cache--cache (make-hash-table))
  (magit-refresh))
```

I can confirm it does happen when calling interactively and when calling with `eval-expression`.

**Comment by vermiculus** [comment]
Actually, nevermind – I found it 😄

**Comment by rosston** [comment]
I just did a bit of manual digging. Looks like it's the `with-temp-buffer` on https://github.com/vermiculus/magithub/blob/master/magithub-issue.el#L85?

**Comment by rosston** [comment]
Perfect, this fixes my issue exactly. Thanks!
