### ISSUE TITLE
magithub-cache no doesn't default to offline mode

### ISSUE THREAD

**Issue by rgrinberg** [vermiculus/magithub#291]
The documentation states that `(setq magithub-cache t)` should make magithub start in cached mode. But this doesn't seem to be the case when I try it. I still get that delay when doing `magit-status` on various repos.

**Comment by vermiculus** [comment]
Bah, that documentation is outdated, then. This is now controlled by the git variable `magithub.cache`.

**Comment by vermiculus** [comment]
Fixed in 8d8d136ae4c380f004354675519f4016c735d78c. Thanks for the report!

**Comment by rgrinberg** [comment]
Awesome! I'm grateful for all the support for us offline mode users. I know you've been hearing quite a lot of complaints about this stuff with regards to just this one feature. Keep up the good work.

**Comment by vermiculus** [comment]
> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.

It's true 😄
