### ISSUE TITLE
Correct error handlers

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#299]
Caused by https://github.com/magit/ghub/commit/6fd4434c2dc7552e24ab31c9a548c3699a5c8b5a

May also need to make changes in ghub+.

**Comment by wbolster** [comment]
i see this after upgrading melpa packages:

```
Error (use-package): magithub/:catch: :condition-case must be a list of error handlers; see the documentation: ((ghub-404 nil))
```

is this what this bug is about or is that something else?

**Comment by vermiculus** [comment]
@wbolster See the ghub commit from above, but that certainly looks related. I think I do indeed check that symbols listed in condition-case are error-symbols (that's in apiwrap.el); since ghub-404 is no longer defined, it's no longer an error symbol.

**Comment by wbolster** [comment]
ok, thanks.

until this issues is properly fixed a `:init` block like this works around the problem:

``` elisp
(use-package magithub
  :demand t
  :after magit
  :init
  ;; fixme this is a temporary hack; see https://github.com/vermiculus/magithub/issues/299
  (define-error 'ghub-404 "Not Found" 'ghub-http-error)
  :config
  (magithub-feature-autoinject t))
```

**Comment by vermiculus** [comment]
@aspiers ^

**Comment by vermiculus** [comment]
This should be fixed with the latest HEAD of ghub+, so I will close this issue. If anyone is still having this problem, please reopen this issue and let me know 😄 

ping @aspiers @seagle0128

**Comment by seagle0128** [comment]
It does work for me.
