### ISSUE TITLE
Offline mode is still very confusing

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#304]
1. The status buffer may contain a `Magithub: OFFLINE...` section. For that to be the case `magithub-offline-p` has to return non-nil.
2. For `magithub-offline-p` to return non-nil `magithub-settings-cache-behavior` has to return `t` or `refreshing-when-offline`.
3. Unless "cache overriding is in affect" (lets assume it is not), `magithub-settings-cache-behavior` returns a representation of the value of `magithub.cache`.
   * `t` for `always`
   * `nil` for `never`
   * `when-present` for `whenPresent` and undefined
4. These values are documented as such:
   *  `always` The cache will not be used, but it will be updated
      * That's really weird because "always" != "do not". Quite the opposite.
   * `never` The cache is never used.  Data is always re-retrieved when online.  When offline, there is simply no data.
   * `whenPresent` The cache is used if it exists.  If there is nothing cached, data is retrieved when online. When offline, there is simply no data.
     * That last sentence doesn't appear to be true.
5. I want to use "offline mode", so after having read these descriptions I have chosen `whenPresent`
   * because, while ambiguous, that comes closest to actually saying "use the cached value, if there is no cached value do NOT retrieve the value from the server".
   * I have NOT chosen `always` because its description very much says that the cached value won't be used, ever.
6. However
   * (5)=`always`="do NOT use cache"(!) ===> (1)="offline"
   * (5)=`whenPresent`=`DO use cache" ===> (1)="online"
7. When you are OFFLINE, then you want to use the cache.
   * And indeed Magithub seems to be doing that. The sections are shown and nothing is being retrieved.
   * However the documentation and the (absence of) the `Magithub: OFFLINE` section disagrees with that.

Please consider using these values instead (and don't map them to booleans, just use these values, as strings, throughou)t:

* `magithub.cache = offline` (or `use`) Use the cached value if any. If there is no cached value, then forgo inserting the section that would need that information to do so.
* `magithub.cache = update-only` Every time the value is needed retrieve it from the server, even when it is already cached locally. However do store the newly retrieved value in the cache, so that it can be used after switching to offline mode.
* `magithub.cache = never` Every time the value is needed retrieve it from the server, even when it is already cached locally. Also do NOT store the retrieved value in the cache.

That last option seems fairly pointless, so I would suggest you replace this with a new variable:

* `magithub.offline = true` Use the cached value if any. If there is no cached value, then forgo inserting the section that would need that information to do so.
* `magithub.offline = false` Every time the value is needed retrieve it from the server, even when it is already cached locally. However do store the newly retrieved value in the cache, so that it can be used after switching to offline mode.

And if you really want to make it possible to retrieve a value without caching it, you could re-add `magithub.cache`, but limit its purpose to what its name and to some extend its possible values always implied:

* `magithub.cache = true` After retrieving a value, do cache it.
* `magithub.cache = false` After retrieving a value, do NOT cache it.

---

And if I am mistaken and the issue actually is that I fundamentally misunderstood something, then please consider that I have spend several hours today reading the source trying to understand what is going on. If that is so, then it would be clear that the documentation has to be massively improved and/or the implementation has to be made easier to understand.

**Comment by tarsius** [comment]
And to cache values during a refresh (for the duration of the refresh), you should use `magit--refresh-cache` instead of rolling your own `magithub-cache--refreshed-forms`. Note however how in this case cache lookup is done shortly before the value would be calculated by other means, while your cache has to be explicitly used by every caller. I think Magit's approach is superior, but it could be rather difficult to change your code to do it like that because you work a lot with wrappers such as `magithub-request` and `magithub-unpaginate`. The right place to implement this in my opinion would be in `ghub+-get` and friends. Somethink like (untested):

```lisp
(defun ghubp-request (method resource params data)
  (let-alist (ghubp-get-context)
    (let ((key (list method resource params data
                     .unpaginate .headers .username .auth .host)))
      (magit--with-refresh-cache key
        ;; ^ Either use the value previously used for KEY during this refresh,
        ;; v or evaluate the body to get it.
        (magithub--with-cache key ; TODO class message after-update
          ;; ^ Either use the value form the cache,
          ;; V or evaluate the body to retrieve it.
          (let ((method (encode-coding-string (upcase (symbol-name method)) 'utf-8))
                (params (apiwrap-plist->alist params)))
            (funcall (or ghubp-request-override-function
                         #'ghub-request)
                     method resource nil
                     :query params
                     :payload data
                     :unpaginate .unpaginate
                     :headers .headers
                     :username .username
                     :auth .auth
                     :host .host)))))))

(defmacro magit--with-refresh-cache (key &rest body)
  ;; Obviously this is oversimplified, see `magit--with-refresh-cache'
  ;; and its callers for inspiration.
  `(or (and (magithub--use-cache-p ...)
            (magithub--get-cached-value ...))
       (let ((value (progn ,@body)))
         (when value
           (magithub--cache-value key value))
         value)))
```

**Comment by tarsius** [comment]
I was wrong about `whenPresent` (I think), but there is still something very weird about `always`.

**Comment by tarsius** [comment]
I found this useful:

```lisp
(defun magithub--debug ()
  (interactive)
  (message "----")
  (message "magithub.cache                            %S"
           (magit-get "magithub.cache"))
  (message "magithub-settings-cache-behavior-override %S"
           magithub-settings-cache-behavior-override)
  (message "magithub-settings-cache-behavior          %S"
           (magithub-settings-cache-behavior))
  (message "magithub-offline-p                        %S"
           (magithub-offline-p)))
```

**Comment by tarsius** [comment]
Just in case... I think Magithub is very nice in general! But the offline stuff seems very weird and the documentation needs a lot of love. And those issues have sadly kept me from really diving in until now.

**Comment by vermiculus** [comment]
Offline is weird. I'm not happy with it yet. Frankly the documentation needs love because I myself am not sure how it works, only that it can work.

**Comment by rgrinberg** [comment]
Wondering if there are any updates here. I'm still not sure how to configure magithub to behave as follows:

Do not make any network requests unless specifically asked to do so. I keep getting random delays when running `magit-status` and I don't know how to fix them.

**Comment by vermiculus** [comment]
Your proposed `magithub.offline` option is making me feel silly, though – I'm still going to see if there are any missed use-cases, but this seems like the simplest option right now. Even if there are missed use-cases, it's likely that `magithub.offline` will exist as a general setting and the more granular ones will override that behavior (offline=6, online=7).

**Comment by vermiculus** [comment]
I remember now why the ability to never use the cache for retrieving data came about: one user (I'd ping if I could find the issue) was confused why refreshing the buffer didn't actually refresh data from GitHub. I obliged at the time, however, it did introduce a *lot* of complexity – for now, I think I'll go back to always using cached data if it exists as in `magithub.offline=false` (which will actually be implemented as `magithub.online=true`.

I'm hoping `magithub-refresh` (to be obsoleted and renamed `magithub--refresh` functionality has matured to the point that the original concern is no longer as dire – I recall it being even more confusing in the past.

**Comment by vermiculus** [comment]
Let me know if the above doesn't make things easier or if something is funky!

**Comment by rgrinberg** [comment]
Congratulations on the wedding.

I think you're on the right track here. May I suggest trying to use magithub in an environment with patchy internet connectivity, perhaps? 😆

**Comment by vermiculus** [comment]
@rgrinberg XD I tried something like that a while ago by installing a throttler – but I never got it working :/ unless you have a favorite by some random chance?
