### ISSUE TITLE
magit-popup-set-variable was removed

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#307]
Magit-Popup 2.12.3 removes `magit-popup-set-variable` and some other functions again. They were already removed in 2.12.1 but had to be restored in 2.12.2 due to packaging issues.

Magithub is using that function and you will have to move it there or use the replacement that are now defined in Magit.

* https://github.com/magit/magit-popup/commit/4c030aca025bcb7a39d43b0db758990963ca3b91
* https://github.com/magit/magit/commit/e95550cd40d866adc1b38c8d94c9504ffe6ac652

**Comment by vermiculus** [comment]
Thanks for letting me know! I'll be in the Netherlands for a week on business so I may not be able to do much, but I'm hoping at least to release a stable version of this package now that 2.12 is out. It's up in the air what I'll be in any condition to do mentally, though; working with a six hour time difference.

**Comment by vermiculus** [comment]
Related magit/magit#3274
