### ISSUE TITLE
Issues and pull requests from the wrong repo when switching project

### ISSUE THREAD

**Issue by xendk** [vermiculus/magithub#31]
Thanks for a nice package. Have been waiting for something like this.

Most of the time when i switch projects (usually using projectile, but opening an file and getting the magit status buffer does the same) shows the issues and pull requests of the previous project (possibly also CI status).

Refreshing using H g does fix this. Seems like an overeager cache issue.

**Comment by vermiculus** [comment]
@xendk Fixed 👍
