### ISSUE TITLE
CI status

### ISSUE THREAD

**Issue by xendk** [vermiculus/magithub#32]
I love the CI status.

We have a lot of projects that have multiple status checks, so I'm waiting for the next version of hub that supports that: https://github.com/github/hub/pull/999

Would be nice if TAB on the CI status line expanded to a list of all statuses, where return on each one would open the associated URL?

Have you considered scrapping the CI url variable, and use the URL returned by hub ci-status -v?

**Comment by vermiculus** [comment]
Re `hub ci-status -v`: nope, didn't know about that one – I'll push that through sometime this week 👍 

Re multiple status checks: can you give me an example of a project that has them? Just need something to test with.

**Comment by xendk** [comment]
Hot off the press: https://github.com/eReolen/ereolen.dk/pull/189

I assume you want to support both formats for the time being, I don't think people upgrade the hub command on day one of a new release.

I'll try out a 2.3.0 pre-release when mgithub supports the new format.
