### ISSUE TITLE
magithub-dashboard opens wrong repo

### ISSUE THREAD

**Issue by Linuus** [vermiculus/magithub#320]
Hi!

If I open a project `Project A` and run `magithub-dashboard` I can see issues assigned to me, like this:
```
Issues Assigned to Me (2)
evil-corp/...
Project B (2)
#123  Some issue
```

Now, if I put the cursor on `Project B` and press `<RET>` it opens the issue list for `Project A`. I believe it should open the issue list of `Project B`, right?

Another thing:

If I put the cursor on `#123  Some issue` above, and press `RET` it opens the issue/PR and if I press `w` it opens the issue/PR in the browser. If I put the cursor on `Project B (2)` above and press `RET` it opens the (wrong) issue list in the browser, and `w` opens the `magit-am-popup`. Shouldn't `w` browse the issue list as well? Otherwise it's a bit confusing to know when to use `w` and when to use `RET`.

NOTE: I'm using evil-magit, perhaps that messes with keybindings?

**Comment by vermiculus** [comment]
This is all very related to #319, so I'll keep most of the discussion there.

This is all stemming from the fact that the github repo context is on `Project A` even inside the `Project B` section. A lot of the repo-specific stuff still doesn't respect thing-at-point – this is probably why you're getting the wrong issue list.

To answer the overall question about UI, yes: you should expect `w` to open the thing-at-point in the browser and `RET` to visit it within emacs (when possible). evil-magit shouldn't impact this, but as I don't use evil, YMMV :-)

**Comment by Linuus** [comment]
Thank your for the answers and this awesome project! I’m really impressed so far!

Just to clarify, that w is not working on Project B is a bug in Magithub?

**Comment by vermiculus** [comment]
If I understand the situation correctly, yes.

**Comment by Linuus** [comment]
Ok, thanks! I'll try to send a PR when I get time to fix it :)
