### ISSUE TITLE
Submit issue after selecting tags

### ISSUE THREAD

**Issue by BrianChristie** [vermiculus/magithub#326]
The documentation is unclear on how to submit an issue after creating it. Documenting here for other folks that run into this:

- After creating the issue, submit it using the appropriate command (C-c C-c, or M-x magithub-edit-submit with a default Spacemacs configuration).
- This opens the Label selection options. Use arrow keys and `RET` to select any desired labels
- Enter `""` in the label field, then `C-RET` to continue submitting

**Comment by vermiculus** [comment]
We should update the actual documentation with this information, so I'll leave the issue open to do that.

https://github.com/vermiculus/magithub/blob/master/magithub.org#creating-an-issue
