### ISSUE TITLE
Rate limited not enabled on github enterprise instances

### ISSUE THREAD

**Issue by diasjorge** [vermiculus/magithub#327]
Hi,

I'm getting the following error from magithub `Magithub is now offline: unknown issue: (ghub-http-error 404 "Not found" ((message . "Rate limiting is not enabled.") (documentation_url . "https://developer.github.com/enterprise/2.12/v3/rate_limit/#get-your-current-rate-limit-status")))`

This happens when I ask magithub to refresh github data.

I think the related code is here: https://github.com/vermiculus/magithub/blob/d9bd5e4bfcab77c021bfb4573173e9bed48269dd/magithub-dash.el#L121

Could we catch the 404 error and set a limit on that case?

**Comment by diasjorge** [comment]
I forgot to mention that data is actually refreshed but you get a prompt saying "Github doesn't seem to be responding"

**Comment by vermiculus** [comment]
Yeah, that's handled 'correctly' here:

https://github.com/vermiculus/magithub/blob/76b0156323c9953a8c6f36ff483a2d528d8df9bc/magithub-core.el#L356

but I'm not a fan of that function in general. Perhaps a ghub-plus function is warranted.

**Comment by vermiculus** [comment]
Related #107.

**Comment by vermiculus** [comment]
Thanks for the report!
