### ISSUE TITLE
"There was an error parsing issues."

### ISSUE THREAD

**Issue by saintaardvark** [vermiculus/magithub#33]
### Description

When running magit-status in a clone of a Github repo, I get a message saying "There was an error parsing issues."  The repo in question is for my Emacs dotfiles:

```
$ git remote -v
origin 	git@github.com:saintaardvark/dot.emacs.d.git (fetch)
origin 	git@github.com:saintaardvark/dot.emacs.d.git (push)
✔ ~/.emacs.d [master|✚ 3]
```

Some things that may be relevant:

- the SSH key I use is password protected
- while I use Hub, I use it for an internal Enterprise Github repo, and I have not set up Hub at all for public Github

Thanks, and I hope this is enough info -- please let me know if you need anything else.

### Backtrace

```
  backtrace()
  magithub-error("failed to parse issue" "There was an error parsing issues.")
  magithub-issue--process-line("github.com username: github.com password for  (never stored): ")
  mapcar(magithub-issue--process-line ("github.com username: github.com password for  (never stored): "))
  magithub-issue-list--internal()
  (progn (when with-temp-message (setq current-message (current-message)) (message "%s" with-temp-message)) (magithub-issue-list--internal))
  (unwind-protect (progn (when with-temp-message (setq current-message (current-message)) (message "%s" with-temp-message)) (magithub-issue-list--internal)) (and with-temp-message (if current-message (message "%s" current-message) (message nil))))
  (let ((with-temp-message "Retrieving issue list...") (current-message)) (unwind-protect (progn (when with-temp-message (setq current-message (current-message)) (message "%s" with-temp-message)) (magithub-issue-list--internal)) (and with-temp-message (if current-message (message "%s" current-message) (message nil)))))
  (with-temp-message "Retrieving issue list..." (magithub-issue-list--internal))
  eval((with-temp-message "Retrieving issue list..." (magithub-issue-list--internal)))
  magithub-cache(:issues (with-temp-message "Retrieving issue list..." (magithub-issue-list--internal)))
  magithub-issue-list()
  magithub-issue--insert-section()
  run-hooks(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-mode-setup-internal(magit-status-mode nil)
  magit-mode-setup(magit-status-mode)
  magit-status-internal("/Users/hubrown/.emacs.d/")
  magit-status("~/.emacs.d")
  (lambda nil (interactive) (magit-status "~/.emacs.d"))()
  funcall-interactively((lambda nil (interactive) (magit-status "~/.emacs.d")))
  call-interactively((lambda nil (interactive) (magit-status "~/.emacs.d")))
  hydra-personal-files/lambda-E-and-exit()
  funcall-interactively(hydra-personal-files/lambda-E-and-exit)
  call-interactively(hydra-personal-files/lambda-E-and-exit nil nil)
  command-execute(hydra-personal-files/lambda-E-and-exit)
```

**Comment by vermiculus** [comment]
I'm really appreciating that backtrace 😄 

It looks like you didn't authenticate `hub`. Run `hub browse` in the terminal and enter your GitHub username/password. Let me know if that works!

**Comment by vermiculus** [comment]
Just out of curiosity, does magithub work with your internal environment? (Just curious -- I've only ever tested with GitHub.com.)

**Comment by saintaardvark** [comment]
Aha, hub authentication was indeed the issue.  Now that I've done that, I've got an extra stanza for github.com in `.config/hub`, and I no longer encounter this error.  Maybe it would be worth adding a more explicit message here? Happy to submit a PR if so.  Alternately, maybe there's some way to catch this output from hub...perhaps in `magithub--hub-command`?  Or by checking whether  `config/hub` has an appropriate entry...  

As for working in the internal github -- no, it doesn't, and I was going to ask whether you'd be interested in a PR to enable it.  AFAICT, the problem is that `magithub-github-repository-p` has a hardcoded check for 'github.com'.  It should be possible (by using [gitconfig.el](https://github.com/tonini/gitconfig.el), for example) to check for a `[hub]` stanza in ~/.gitconfig.  Mine looks like this:

```
[hub]
	host = github.internal.example.com
```

...so it should be fairly simple to add that as a host/URL to check for.

Thanks very kindly for the quick response!

**Comment by vermiculus** [comment]
Checking config files seems like the way to go. I've opened a new issue above. Please chime in there!
