### ISSUE TITLE
Don't use debugging advice by default

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#333]
This line in `magithub-core.el` is probably a leftover and should be removed.

```lisp
(advice-add #'ghub-request :around #'magithub-debug--ghub-request-wrapper)
```

As a side-note, that advice was pretty confusing when first running into it when debugging a bug in `ghub` itself, so I am currently removing it in my init file.

**Comment by vermiculus** [comment]
It wasn't unintentional; what problems is it causing?

**Comment by tarsius** [comment]
If a user reports a bug report against `ghub` or `magit` and has `magithub` loaded too, then the backtrace contains unrelated things, which makes it harder to figure out if the bug is in my code or not.

**Comment by vermiculus** [comment]
Would it be helpful if this were relegated to a command like `magithub-instrument-for-debugging`.

**Comment by tarsius** [comment]
Yes that would be great.

**Comment by tarsius** [comment]
Ping.

(I'll try to respond to your email soon.)

**Comment by vermiculus** [comment]
Thanks for the ping :-)
