### ISSUE TITLE
Cannot get CI Status to Display

### ISSUE THREAD

**Issue by jeffjewiss** [vermiculus/magithub#334]
Hi, I'm really enjoying using Magithub so far, thanks for putting so much time into this.

I'm stuck on trying to get CI status to display for PRs. I'm pretty sure I have my token setup properly with ghub because I can view issues and PRs for some public and private repos, so I can see that requests are being made to the GitHub API correctly.

However, my PRs don't have a CI status, so I've been trying to run `magithub-ci-pr-status`, which then shows the dialog for a GitHub token not being available.

Is there some configuration I'm missing to get this to work?

Thanks!

**Comment by jeffjewiss** [comment]
Yeah, I'll do my best to provide more detail.

I'm using [doom-emacs](https://github.com/hlissner/doom-emacs) for my config.

An example would be opening this repo: https://github.com/jeffjewiss/ember-cli-postcss/ (master) and then opening the magit-status buffer. The issues and pull requests are successfully downloaded and populated in that buffer. If I open the 1 open pull request (RET) there is no CI status. So from the PR detail view I try to run `magithub-ci-pr-status` and I'm presented with the dialog buffer that there's no token and it prompts me to create one. I've gone through the dialog without success (pretty sure this is due to 2-factor auth), but I do have a token in `.authinfo`, which should be working since I can also get issues and pull requests for private repos.

**Comment by vermiculus** [comment]
This is PR116 in that repo, for posterity.

I've thought about adding CI status to the PR detail buffer for a long time, but haven't had the time to do it. Right now, you should switch to the branch that's tracking the PR -- does that give you the right status in the status buffer?

**Comment by jeffjewiss** [comment]
Unfortunately even when switching to that branch I don't see any CI info in the magit status buffer.

Yeah, sorry, looks like I initially expected to see the CI status in a few places where it isn't implemented yet. So far I'm unable to see it anywhere though, which I think added to my confusion on how the feature works. :-)

Thanks for looking into this, appreciate it!

**Comment by jeffjewiss** [comment]
I'm going to close this as I'm seeing some CI Status messages, and I think I know the cause for why I wasn't.

Does the ci status check by looking at the remote push that's set for each branch? Out of habit I had only been setting and pushing to an upstream. Once I set this in the Magit status buffer with `P p` I was seeing CI status messages reliably.

So I think this came down to my unfamiliarity with Magit and some assumptions I had as to how the status worked.

Thanks for your help in looking into this.
