### ISSUE TITLE
Issues and pull requests not shown in repos I own

### ISSUE THREAD

**Issue by tohojo** [vermiculus/magithub#342]
It seems that when I open a magit buffer for a repository that I own myself, I
get issue and pull requests sections in the status buffer. Whereas if I open a
repo I don't own, I do.

I have not been able to figure out why that is. Help? :)

**Comment by tohojo** [comment]
Hmm, turns out the section hook was not being installed properly in some cases.
Managed to fix that, so everything is working now :)

**Comment by vermiculus** [comment]
Do you know if this was an issue with your configuration or is there some follow-up that can be done here?

**Comment by tohojo** [comment]
I think it was an issue with my configuration. The reason I was seeing the
issues in some repos was that the magit-status-sections-hook is buffer-local,
and so the buffers that I already had open when running
magithub-feature-autoinject weren't updated.

After making sure the autoinject hook was run correctly in my init, and
restarting emacs, everything works as its supposed to :)

**Comment by vermiculus** [comment]
Awesome, and a likely explanation 😄
