### ISSUE TITLE
Issue list display issues

### ISSUE THREAD

**Issue by rgrinberg** [vermiculus/magithub#350]
I've already made an issue about the main source of slowness for me when rendering the issues list but there are some secondary issues.

It turns that displaying long lists of issues is quite time consuming by itself. One of the reasons is that by default magithub spends quite a lot of time rendering every issue nicely and colorizing things. Is it possible to make this behavior more lazy? What would be a lot better if the fancy propretizing occurred only when expanding the issue.

Additionally, I think that it would make sense to limit the number of issues displayed at least until this is really speedy. I recommend doing it the way magit handles long commit logs. Truncate at some number X (around 20?) and then allow the user to expand the issue list with `+` or something.

PS: I assume the same issue occurs with PR's, but I don't really have any repos with such a huge number of PR's to make a difference.

**Comment by vermiculus** [comment]
I don't think the process can be made lazier without updates to the magit-section plumbing (and I know this is something that's been on @tarsius's mind). The best way for you to speed up display is to apply issue-filtering (`magithub-issue-issue-filter-functions`) or customizing `magithub-issue-details-hook` to remove unneeded sections.

The truncation stuff is tracked in #166.
