### ISSUE TITLE
Missing quotes in calls to magit-insert-headers

### ISSUE THREAD

**Issue by duog** [vermiculus/magithub#359]
It seems that your two calls to magit-insert-headers in `magithub-dash.el` and `magithub-issue-view` should quote the hook variable.

I see the following:
```
magit-insert-headers: Wrong type argument: symbolp, (magithub-dash-insert-user-name-header magithub-dash-insert-ratelimit-header magithub-maybe-report-offline-mode)
```
When opening the magithub dashboard, and adding said quotes seems to fix it.

I'm on linux, emacs 26.1 and am getting magithub from melpa.

**Comment by seanfarley** [comment]
I was about to open the same issue since I just hit this; so I'm just here to confirm!

**Comment by vermiculus** [comment]
It's odd that this is happening all of a sudden. @tarsius – did I miss a plumping change upstream? I haven't updated magit in a few days (lagging about a week behind) and everything's working fine for me.

**Comment by duog** [comment]
Pretty sure it's https://github.com/magit/magit/commit/2fc79d0826575017b09c2d3a26980f0fa5dfaf8d

**Comment by tarsius** [comment]
Indeed. @vermiculus you'll have to quote the argument to `magit-insert-headers`.
