### ISSUE TITLE
error "apply: Searching for program: No such file or directory, hub"

### ISSUE THREAD

**Issue by Silex** [vermiculus/magithub#36]
When `hub` is not installed, there's this big error which prevents magit from working properly.

Is it possible to turn this into a `message` instead?

**Comment by vermiculus** [comment]
Yes, the hooks and such should probably assume no setup.

**Comment by Silex** [comment]
By the way, great package :+1: 

A bit slow sometimes but can be disabled easily with <kbd>H `</kbd>

**Comment by vermiculus** [comment]
The slowness is something I'm working on, but there's only so much I can do 😄 most of the pauses come from `hub`.

**Comment by Silex** [comment]
Making it async would solve the slow feeling :wink:

**Comment by vermiculus** [comment]
Do you wanna talk about this on gitter? I'm not sure how it can be made async and still maintain functionality.

**Comment by Silex** [comment]
I don't have a gitter account... but I imagine something like `magit-status-hook` starts an async task that when done finds the magit-status buffer and adds the relevant section.

That or you always display the section with a text like "refreshing..." and when the async task is done you refresh the status buffer.

**Comment by vermiculus** [comment]
> I don't have a gitter account

No such thing; it uses GitHub. To each their own though; I'm fine like this.

> but I imagine something like `magit-status-hook` starts an async task that when done finds the magit-status buffer and adds the relevant section.

Harder than you might think – I'd have to hook into `magit-section`'s internal data structure to make navigation work right…

> That or you always display the section with a text like "refreshing..." and when the async task is done you refresh the status buffer.

…but *that* could be a workable idea. We could use that 'refreshing…' text with a special marker for the sentinel to find it again. We still run into the problem of interfacing into `magit-section`, but at least we're already in our own section at that point and can't mess anything up 😄 

All this discussion should probably go in a new issue though.

----

For this issue, does the above work for you?

**Comment by Silex** [comment]
>> I don't have a gitter account

> No such thing; it uses GitHub. To each their own though; I'm fine like this.

Well, went there and it said "Sign in to start talking". I guess I can sign in with my github account, but I didn't quite see the advantage compared to discussing it here.

>> but I imagine something like magit-status-hook starts an async task that when done finds the magit-status buffer and adds the relevant section.

> Harder than you might think – I'd have to hook into magit-section's internal data structure to make navigation work right…

Well, you know better than me but from a quick look at the code, it looks like you could change `(add-hook 'magit-status-sections-hook #'magithub-issue--insert-section t)` into something like `(add-hook 'magit-status-sections-hook #'magithub-issue--insert-section-only-if-data-are-ready t)` and have the async task refresh the magit status buffer when it is done.

Of course, refreshing the magit status buffer is maybe not desirable, because maybe it messes with what the user started doing while magithub was refreshing. I don't know how well magit preserves scrolling & sections, etc.

>> That or you always display the section with a text like "refreshing..." and when the async task is done you refresh the status buffer.

> …but that could be a workable idea. We could use that 'refreshing…' text with a special marker for the sentinel to find it again. We still run into the problem of interfacing into magit-section, but at least we're already in our own section at that point and can't mess anything up 

It also makes more sense interface wise, because we know we can expect something to appear there. Again, I'm not familiar enough with magit-section to really see how difficult it is... I just assume each section is refreshable independently, if you want better advice you should ask tarsius he's usually very helpful with guidance on how to do achieve certain things.

> All this discussion should probably go in a new issue though.
> For this issue, does the above work for you?

Looks alright to me. Thanks!
