### ISSUE TITLE
(Feature Request) Copy github url of buffer file and put it in kill-ring.

### ISSUE THREAD

**Issue by RenWenshan** [vermiculus/magithub#387]
I have some a self defined command that puts the github URL of current buffer file into the kill-ring. Recently I started using magithub (thanks for the awesome work!) and it has a command `magithub-browse-file` which has similiar functionality but it opens the URL in a browser instead.

Can we separate the logic of constructing the url (maybe a function `magithub-browse-file--get-url`) so people can make use of its result?

**Comment by vermiculus** [comment]
Nice idea – done! 👍
