### ISSUE TITLE
Not clear how to initialize hub

### ISSUE THREAD

**Issue by keisetsu** [vermiculus/magithub#39]
This looks great! I think the issue browsing would be a big help (trying to stay in emacs as much as possible!)
However, I'm probably being dense but I can't figure out how to initialize hub. The docs mention running hub browse in a terminal, and I have run this in a terminal, then run emacs from the same terminal, run a terminal inside emacs (`M-x term`) and run `hub browse` from there (which works fine) and then opened magit-status, but magithub always says "Hub hasn't been initialized yet, aborting".

It may or may not be important, but I use two-factor authorization using a github token. I provide this token to hub through an environment variable, and as I said this works fine in a simple terminal or in an emacs terminal.

Could you provide a more detailed explanation of "To force hub to authenticate, you can use hub browse in a terminal (inside a GitHub repo)."

Thanks!

**Comment by vermiculus** [comment]
If you're providing this via an environment variable, it sounds like emacs isn't picking it up (much like the `PATH` problems that plague general emacs newcomers). If I remember correctly, `M-x term` is still an interactive login terminal that will pick up your configuration.

For the moment, I'd recommend against the environment variable approach and allow hub to write to `~/.config/hub`. I'll look into the environment variables (which I don't use myself) a little more later today after I tend to other domestic duties 😄

**Comment by keisetsu** [comment]
Thanks for the quick reply.
Ok, I didn't get that hub will get a token itself! I prefer that anyway.

I've got further problems below, but I just realized I'm using the 2.3 release of hub, and that may be causing the problem. If you want to go ahead and close this, I'll just run hub from a terminal (I mainly want the issue stuff anyway, and the cli will be more powerful anyway), but I'll go ahead and include the debug below.

---

I'm now having a problem with getting the issue list. It complains hub didn't have any response from ci-status. However, running from the terminal I get "success".

Actually, looking at the error report it looks like it's failing on one of the issues:
`Block signups and email changes to @<mydomain> emails` (I've chosen to hide details, but there's a regular domain name where `<mydomain>` is).

This is the first issue in the list, so it may just be that hub output has changed in the newer versions.

Please note in the following I've removed all the issues and replaced them with `...` 
## Automated error report

### Description

Using magithub to check issues

### Backtrace

```
  backtrace()
  magithub-error("failed to parse issue" "There was an error parsing issues.")
  magithub-issue--process-line("  #11101  Block signups and email changes to @<mydomain> emails   priority: this week ")
  mapcar(magithub-issue--process-line ("..."))
    magithub-issue-list--internal()
  (progn (when with-temp-message (setq current-message (current-message)) (message "%s" with-temp-message)) (magithub-issue-list--internal))
  (unwind-protect (progn (when with-temp-message (setq current-message (current-message)) (message "%s" with-temp-message)) (magithub-issue-list--internal)) (and with-temp-message (if current-message (message "%s" current-message) (message nil))))
  (let ((with-temp-message "Retrieving issue list...") (current-message)) (unwind-protect (progn (when with-temp-message (setq current-message (current-message)) (message "%s" with-temp-message)) (magithub-issue-list--internal)) (and with-temp-message (if current-message (message "%s" current-message) (message nil)))))
  (with-temp-message "Retrieving issue list..." (magithub-issue-list--internal))
  eval((with-temp-message "Retrieving issue list..." (magithub-issue-list--internal)))
  magithub-cache--table(#s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data (:ci-status ((22521 15170 954741 814000) . internal-error))) :issues (with-temp-message "Retrieving issue list..." (magithub-issue-list--internal)))
  magithub-cache("https://github.com/<my repo>" :issues (with-temp-message "Retrieving issue list..." (magithub-issue-list--internal)))
  magithub-issue-list()
  magithub-issue--insert-section()
  run-hooks(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-mode-setup-internal(magit-status-mode nil)
  magit-mode-setup(magit-status-mode)
  magit-status-internal("~/<mydir>")
  magit-status(nil)
  funcall-interactively(magit-status nil)
  call-interactively(magit-status record nil)
  command-execute(magit-status record)
  execute-extended-command(nil "magit-status" "magit-stat")
  funcall-interactively(execute-extended-command nil "magit-status" "magit-stat")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by vermiculus** [comment]
Ah, ok – I see what's going on here. We've got some version skew.

I'm on hub 2.2.8 – this is what `hub issue` gives me in this repository:

```
     39] Not clear how to initialize hub ( https://github.com/vermiculus/magithub/issues/39 )
     37] Async loading ( https://github.com/vermiculus/magithub/issues/37 )
     35] Local CI-Status ( https://github.com/vermiculus/magithub/issues/35 )
     32] CI status ( https://github.com/vermiculus/magithub/issues/32 )
     28] Settings console ( https://github.com/vermiculus/magithub/issues/28 )
     24] Collapse full 40-char commit hashes into something more readable ( https://github.com/vermiculus/magithub/issues/24 )
     23] Reference issues and pull-requests with # ( https://github.com/vermiculus/magithub/issues/23 )
     19] Don't unfill code blocks ( https://github.com/vermiculus/magithub/issues/19 )
     18] Our own GitHub-Message mode ( https://github.com/vermiculus/magithub/issues/18 )
     17] Investigate undercover.el ( https://github.com/vermiculus/magithub/issues/17 )
     15] Add labels to issues from the edit buffer ( https://github.com/vermiculus/magithub/issues/15 )
     14] Fetch branches of pull requests from magit-status ( https://github.com/vermiculus/magithub/issues/14 )
      9] Use .github/ templates ( https://github.com/vermiculus/magithub/issues/9 )
      6] Dynamically retrieve issue label list ( https://github.com/vermiculus/magithub/issues/6 )
```

Thus, I use the first `]` and the last `(` to mark the different parts of the output. From the line you gave, your format is quite different – it's not processable by the current code.

I'll see what I can do to handle multiple different versions of hub today instead – I do know that later versions of hub allow a `--format` for issues which will make things a little easier – the only problem is detecting the version.

Since the authentication problems have been solved, I'll open a new issue for tracking. Thanks!!
