### ISSUE TITLE
Proxy documentation section is outdated.

### ISSUE THREAD

**Issue by junjizhi** [vermiculus/magithub#390]
The proxies section in the [manual](https://github.com/vermiculus/magithub/blob/master/magithub.org#proxies)
mentions a function `magithub-proxy-set-default` which doesn't exist any more.

This comes from the discussion in https://github.com/vermiculus/magithub/issues/66#issuecomment-439483730

**Comment by vermiculus** [comment]
Fixed in #391; thanks!
