### ISSUE TITLE
Issue closing error

### ISSUE THREAD

**Issue by mgcyung** [vermiculus/magithub#397]
It says "user-error: Cannot close this issue: not the issue owner or an administrator of this repo" when I close a issue created by me.

**Comment by mgcyung** [comment]
Can not close a issue by 'magithub-issue-close'. The error says
"user-error: Cannot close this issue: not the issue owner or an
administrator of this repo". The issue is created by myself such as
the one we are in.

**Comment by mgcyung** [comment]
Such as the current issue
https://github.com/vermiculus/magithub/issues/397.

**Comment by vermiculus** [comment]
What does `(let-alist (magithub-user-me) .user.login)` evaluate to for you? If that's nil, how about `(let-alist (magithub-user-me) .login)`?

**Comment by vermiculus** [comment]
Should be fixed with the next MELPA update. Thanks for the report!

**Comment by mgcyung** [comment]
Yes, it works now. Thanks for the great work.
