### ISSUE TITLE
Support more recent versions of hub

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#40]
Spawned from #39 – I'll need to detect the version of hub before attempting to use it to retrieve issues – it looks like the default format changes from 2.2.8 to 2.3.

**Comment by keisetsu** [comment]
Looks like you might need to update the ci status code, too. Not sure what 2.2.8 outputs, I just get `success` from 2.3.0  on the command line.

**Comment by vermiculus** [comment]
That's what happens for 2.2.8 as well. What kind of error is magithub giving you?

**Comment by vermiculus** [comment]
@keisetsu I've added support for hub 2.3+ and I've tested it, but I'm not able to reproduce your problems with CI status – can you provide more details about what's gone wrong?

**Comment by vermiculus** [comment]
This is turning out to be more complicated than I anticipated. For some absurd reason, hub's output is not symmetric using `--verbose` vs. not. I'll need to think up a good UI for this before I proceed further.
