### ISSUE TITLE
magithub-feature-autoinject error

### ISSUE THREAD

**Issue by mgcyung** [vermiculus/magithub#402]
Emacs initialization breaks down on
``` emacs-lisp
(after-load 'magit (magithub-feature-autoinject t))
```
with error
```
error: feature pull-request-merge failed to install: nil
```
It seems due to no defination of function "magit-am-popup". Since https://github.com/magit/magit/pull/3728 magit uses Transient instead of Magit-Popup.

**Comment by vermiculus** [comment]
You're right; magithub will need to be ported to transient. I'm unlikely to do this anytime in the next few days ago (what little free time I have, I'm putting into Forge) – do you want to take a crack at a PR? You'll want to adjust `magithub-feature-list` in magithub-core.el.
