### ISSUE TITLE
Warning: ‘magit-git-output-coding-system’ is an     obsolete variable (as of Magit 2.9.0); use ‘magit-log-output-coding-system’ instead.

### ISSUE THREAD

**Issue by ackalker** [vermiculus/magithub#41]
First off, thanks for creating this package :-)

When I updated magithub from MELPA today, I received the following warning:
```
Compiling file /home/miki/.emacs.d/elpa/magithub-20161010.2135/magithub.el at Tue Oct 11 15:18:41 2016

Compiling no file at Tue Oct 11 15:18:42 2016

In magit--process-coding-system:
magit-process.el:701:18:Warning: ‘magit-git-output-coding-system’ is an
    obsolete variable (as of Magit 2.9.0); use
    ‘magit-log-output-coding-system’ instead.
```

Perhaps this is a known issue, or is not an issue because of backwards compatibility, but I'm reporting it just in case.

**Comment by vermiculus** [comment]
Ah, I grabbed the let-bind from an earlier version of magit -- this should be pretty easy to fix. Thanks for reporting!

**Comment by ackalker** [comment]
You're welcome ;) Thanks for the very quick reaction!

**Comment by vermiculus** [comment]
I'd thought this was related to the let-bind in `magithub-core:command-*` functions, but actually, this looks like an issue with Magit. @tarsius, can you confirm?

I don't reference this variable anywhere in Magithub.

**Comment by tarsius** [comment]
Recompiling `magithub` should fix the issue I think (until you do the byte-compiled code continues to contain the expansion of a macro which has since been modified).

**Comment by vermiculus** [comment]
Thanks!

@ackalker I've found some more bugs since last night, so MELPA should be updating shortly. Let me know if this issue persists after updating (and via package.el, recompiling) -- I'll reopen -- but I'm closing this issue for now as there is no apparent follow-up.

**Comment by ackalker** [comment]
@vermiculus Thanks again for the quick reply :)
I just pulled package updates again, no problem whatsoever for magithub, but a somewhat strange error for magit instead:
```
Wrote /home/miki/.emacs.d/elpa/magit-20161011.1700/magit-autoloads.el
Error in package--load-files-for-activation: (cyclic-variable-indirection magit-git-output-coding-system)
Loading async...done
Symbol’s chain of variable indirections contains a loop: magit-git-output-coding-system
```

**Comment by vermiculus** [comment]
It's possible, though I can't say I understand what's being reported (i.e., I don't know what 'variable indirection' properly is.)

If it becomes a problem, I'd raise on magit's gitter chat or as an issue there 😄
