### ISSUE TITLE
magithub--edit-file-type does not account for .git being a file

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#48]
The actual gitdir does not have to be located inside the working tree.  The .git inside the working tree may also be a file whose contents sais where the real gitdir is (a long time ago a symlink was used, but Windows...).  This mechanism is used, for example, for submodules and alternative working trees.  An example:

I have installed magithub as a submodule at

    ~/.emacs.d/lib/magithub/

and

    ~/.emacs.d/lib/magithub/.git

is a file, and the real gitdir is at

    ~/.emacs.d/.git/modules/magithub/

So this will fail:

    (s-suffix? "/.git/" (file-name-directory path))

**Comment by vermiculus** [comment]
Oh goodness… that makes things a little more nuanced.

In modules/magithub, what does `git rev-parse --git-dir` give you? I just need a way to determine that we're in the root of the `.git` repo-guts.

**Comment by vermiculus** [comment]
Or better yet, what does `git rev-parse --is-inside-git-dir` give you?

**Comment by tarsius** [comment]
> Or better yet, what does `git rev-parse --is-inside-git-dir` give you? (I get false, somehow, but I may be misunderstanding.)

See https://github.com/magit/magit/commit/8c39a4a1b56ee943f4cf7f087ea268d8f7fbdc96.

**Comment by vermiculus** [comment]
`magit-git-dir` seems like my ticket to happy fun times, then 👍 I'll get a patch in tonight.

**Comment by tarsius** [comment]
Or why not just the updated `magit-inside-gitdir-p` itself?

**Comment by vermiculus** [comment]
Because the file should be `/.git/FILE` -- not `/.git/subdir/FILE`, etc.

**Comment by tarsius** [comment]
In this case `subdir` is actually `modules/magithub` and here `magithub` *is* a "git dir", equivalent to `magithub/.git/`. The file being edited is `~/.emacs.d/.git/modules/magithub/ISSUE_EDITMSG`.

**Comment by vermiculus** [comment]
Ah... hm. Then yes -- `magit-inside-gitdir-p` is the best solution 👍

**Comment by vermiculus** [comment]
Works like a charm, but I won't be able to merge this in until magit/magit#2827 is in as well.

**Comment by tarsius** [comment]
I was just about to ;-) Note that users who have updated Magit yesterday and you update (just) Magithub today will still run into this short-lived bug. That's a limitation of Melpa (unstable)/`package.el`; `package.el` does not update dependencies unless the required version is bumped and Melpa snapshot "versions" are always higher than whatever the recipe may specify (`YYYYMMDD > M.N.O`). For Magit I perform [this dance](https://github.com/magit/magit/commit/0dcebfe75e8746ce26bda650b45d476e4cdb0b1b) after every release, but I don't recommend that for packages that aren't nearly as widely used.

**Comment by vermiculus** [comment]
I'll paste the error people will get in here for the search engines:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  find-file-name-handler(nil file-in-directory-p)
```

That way folks can just know to update Magit 👍

I find it odd that folks would update one without the other, so I'm not too concerned with this possibility 😄
