### ISSUE TITLE
Show issue and pr counts in magit-list-repositories

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#49]
You'll have to implement `magithub-repolist-column-issue` and `magithub-repolist-column-pull-request`.

**Comment by vermiculus** [comment]
How exactly can I use `magit-list-repositories` to test? When I run that command, it always gives me a blank tabular.

**Comment by tarsius** [comment]
This command will now tell you that! But while we are waiting for Melpa to rebuild, here's what you would be told now: "You need to customize `magit-repository-directories` before you can list repositories".

**Comment by vermiculus** [comment]
Ah, so is `magit-repository-directories` effectively a list of repositories you actually care about and `magit-list-repositories` is like a summary of those repositories?

**Comment by tarsius** [comment]
Exactly.
