### ISSUE TITLE
Entering issue label prompt non-responsive.

### ISSUE THREAD

**Issue by chase-dwelle** [vermiculus/magithub#56]
When I go to create an issue, I get prompted to enter a label name via:

`--label=... Issue labels (or "" to quit):`

However, when entering a label name (already existing in my repository, with or without quotes), there is no response: the mini-buffer does not change, just giving me the same prompt. The same thing happens when I enter `""` to quit the mini-buffer, and I therefore need to use `C-g` to exit and get back to the magithub buffer.

Based on the prompt, I am assuming the correct usage is to:
1. Enter the label name(s) in quotes (e.g, `"enhancement")
2. Once finished entering label name(s), quit the mini-buffer by entering `""`.

This could be an issue with my `emacs` setup, but I want to make sure I am using the correct behavior before trying to fix it within `emacs`.

**Comment by vermiculus** [comment]
Are you entering 'nothing' (i.e. null string i.e. `""`) or literally `""`? The prompt is expecting null string to mean 'done'.

**Comment by chase-dwelle** [comment]
Yes, I was literally entering `""`, and was also entering the label names surrounded by quotes. So the correct way to do this is to:

1. Enter the label name(s) in *without* quotes (e.g, `enhancement`)
2. Once finished entering label name(s), quit the mini-buffer by pressing return once more. This populates the label option as, e.g., `--label="enhancement"`.
