### ISSUE TITLE
Request: Use upstream instead of master as the default base for PRs (if it differs from current branch)

### ISSUE THREAD

**Issue by Malabarba** [vermiculus/magithub#58]
Hi Sean,

At work, I frequently create PRs that go on a `feature/` branch instead of going on master.
However, when creating a PR with `H p`, I have to specify the base branch every time (magithub defaults to master).

I've locally defined this `feature/` branch as the upstream of the branch I'm working on locally, so I think magithub should default to using that as the base for the PR (instead of using `master`).

Cheers, and thanks for the package! :-)

**Comment by vermiculus** [comment]
Would you say it's always more appropriate to use `upstream` than anything else? I'm debating whether or not to introduce a variable to customize; from what I can tell, I think it's more useful to the vast majority to just hard-code the behavior you describe – but you may have a more diverse experience.

**Comment by vermiculus** [comment]
One concern I do have: if upstream is determined when the popup displays and the users changes and saves settings, the upstream branch will be saved as the `--base=` value for this popup regardless of what branch you're on.

It would certainly help to do this, but would it be sufficient to introduce some sort of 'cookie' that can be replaced with upstream when the action is actually taken? Something like

```
Switches
 -f Ignore unpushed commits (-f)
 -o Open in my browser (-o)

Options
 =b Base branch (--base=$(magit-get-upstream-branch))
 =h Head branch (--head=)

Actions
 P Submit a pull request
```

**Comment by Malabarba** [comment]
> Would you say it's always more appropriate to use upstream than anything else?

1. If upstream has the same name as the local branch, **and** its remote is the pushRemote, then it probably not appropriate. In that scenario you would be opening a PR from a branch to itself.
2. Otherwise, I think it would be a more appropriate default. 

> One concern I do have: if upstream is determined when the popup displays and the users changes and saves settings, the upstream branch will be saved as the --base= value for this popup regardless of what branch you're on.

I'm not versed enough in magit internals to know what to do about that. Maybe there's already a way that you're not aware of. =/

**Comment by fommil** [comment]
I think I'm also seeing this... but for all features. When I tried out magithub today (which looks awesome btw!) I didn't see any of the issues or pull requests for the upstream.

My workflow is that I tend to work on my own fork of a main repo, and all PRs/issues/etc are on the upstream.

**Comment by vermiculus** [comment]
@fommil That's a different issue, I think: this thread is about customizing a default branch *in this repository* for `--base=` while you're asking about getting issues/pulls from a different repo *entirely*. The second request is actually easier – could you create an issue for it?

**Comment by fommil** [comment]
Oh! Will do :smile:
