### ISSUE TITLE
Dynamically retrieve issue label list

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#6]
28aa45709beee7c2e207f7c626d76a12dfe13fcd introduced adding labels to
new issues.  However, `hub` isn't yet able to provide a list of labels
specific to this repository.

Other means of getting this information may be possible.

**Comment by vermiculus** [comment]
In the meantime, you can just enter a label that doesn't exist yet. Hub will apply that label.

**Comment by jgkamat** [comment]
Hub still dosen't have support for this yet, but it's possible to get a list of labels through the github api via 
`/repos/user/reponame/labels`

**Comment by vermiculus** [comment]
Yep, see the linked hub-issue above.
