### ISSUE TITLE
Magit-over-TRAMP: `H H' opens browser on remote machine

### ISSUE THREAD

**Issue by dabrahams** [vermiculus/magithub#62]
On my Mac, doing magit-status in a TRAMP remote directory works great.  When I hit \`RET' on any of the pull requests I see listed there, they open in a browser on my local machine.  However, \`H H' opens a browser on the remote machine!

**Comment by vermiculus** [comment]
Hah! That's a new one – but I think I know why it's happening:
* `magithub-issue-browse` gets the URL from the issue and calls `browse-url` on it (which is more than likely TRAMP-aware)
* `magithub-browse` uses `hub browse` directly, which is probably not aware of being run over SSH

This can be worked around by changing the definition of `magithub-browse` to pass `hub browse -u` output to `browse-url`.

**Comment by vermiculus** [comment]
Let me know if the above doesn't work for you; frankly I've no way to test that the fix works.
