### ISSUE TITLE
Spurious exuberant "missing" magithub-features

### ISSUE THREAD

**Issue by idcrook** [vermiculus/magithub#64]
After updating through latest magithub (`magithub-20170115.1723`) through ELPA package manager, I started getting messages quite often. It seems to happen when using any `magit` operation, with over a page of modules trimmed in example message below.

In **\*Messages\***
`Magithub features not configured: (helm-org markdown-mode ... 
cocoa ns multi-tty make-network-process emacs); see variable ‘magithub-features’ to turn off this message`

```
magithub-features is a variable defined in ‘magithub.el’.
Its value is nil

Documentation:
An alist of feature-symbols to Booleans.
See ‘_magithub-feature-list_’.
```
 _magithub-feature-list_ --->
```
magithub-feature-list is a variable defined in ‘magithub.el’.
Its value is (pull-request-merge pull-request-checkout)
```
`magithub-feature-list` seems to be properly defined?

It doesn't seem to cause any issues other than blowing up my **\*Messages\*** but I am not a fan of this new "feature"... 😄

**Comment by vermiculus** [comment]
Hm, I'm not able to reproduce this. When I take out the new `magithub-feature-autoinject` function call from my config, I just receive the following message on an idle timer:

    Magithub features not configured: (pull-request-merge pull-request-checkout); \
    see variable ‘magithub-features’ to turn off this message

Blowing up your `*Messages*` was certainly not my intended change! 😄 Are you able to reproduce with `emacs -Q`?

**Comment by gergelypolonkai** [comment]
+1 on the issue. Happens using `emacs -Q`, too:

    Magithub features not configured: (magithub magithub-ci magithub-issue magithub-cache magithub-core s magit-obsolete magit-blame magit-stash magit-bisect magit-remote magit-commit magit-sequence magit-notes magit-worktree magit-branch magit-files magit-refs magit-status magit package seq magit-repos magit-apply magit-wip magit-log magit-diff smerge-mode diff-mode magit-core magit-autorevert autorevert filenotify magit-process magit-margin magit-mode magit-git crm magit-section magit-popup git-commit magit-utils log-edit easy-mmode message rfc822 mml mml-sec epg epg-config mm-decode mm-bodies mm-encode mail-parse rfc2231 rfc2047 rfc2045 ietf-drums mailabbrev mail-utils gmm-utils mailheader pcvs-util add-log with-editor tramp-sh tramp tramp-compat auth-source cl-seq eieio byte-opt bytecomp byte-compile cl-extra cconv eieio-core cl-macs gv gnus-util mm-util help-fns mail-prsvr password-cache tramp-loaddefs trampver ucs-normalize shell pcomplete comint ansi-color ring format-spec advice server dash help-mode easymenu debug misearch multi-isearch dired-aux cl-loaddefs pcase cl-lib dired time-date mule-util tooltip eldoc electric uniquify ediff-hook vc-hooks lisp-float-type mwheel x-win term/common-win x-dnd tool-bar dnd fontset image regexp-opt fringe tabulated-list newcomment elisp-mode lisp-mode prog-mode register page menu-bar rfn-eshadow timer select scroll-bar mouse jit-lock font-lock syntax facemenu font-core frame cl-generic cham georgian utf-8-lang misc-lang vietnamese tibetan thai tai-viet lao korean japanese eucjp-ms cp51932 hebrew greek romanian slovak czech european ethiopic indian cyrillic chinese charscript case-table epa-hook jka-cmpr-hook help simple abbrev minibuffer cl-preloaded nadvice loaddefs button faces cus-face macroexp files text-properties overlay sha1 md5 base64 format env code-pages mule custom widget hashtable-print-readable backquote dbusbind inotify dynamic-setting system-font-setting font-render-setting xwidget-internal move-toolbar gtk x-toolkit x multi-tty make-network-process emacs); see variable ‘magithub-features’ to turn off this message

I looked at the variable, too; `magithub-features` said to be "An alist of feature-symbols to Booleans." (whatever that means), and references `magithub-feature-list`, which is "Not documented as a variable." (but is risky to be used as file-local.)

I can live with it, but it’s annoying as hell, as I have 100+ installed packages, and this message gets really huge, temporarily expanding my message bar whenever I do something in magit, even if I’m not in a GitHub-based repository.

**Comment by gergelypolonkai** [comment]
Quick thought comes to mind: @vermiculus do you set `magithub-features` in your own config to something, or just use it unset as I do?

**Comment by vermiculus** [comment]
`magithub-features` is a list of symbols representing the features that have been 'injected' into magit workflows (i.e., actions added to `magit-*-popup`). I've not set the variable myself; it's completely managed by the package.

I'm not able to reproduce either way, but this might give me a clue (eventually, when I'm awake): is the problem helped at all if you add a call to `(magithub-feature-autoinject t)` in your config?

I'm just very confused by this issue since the only time this nag notification is triggered is here:

```elisp
(defun magithub-issue--insert-pr-section ()
  "Insert GitHub pull requests if appropriate."

  (magithub-feature-maybe-idle-notify
   'pull-request-merge
   'pull-request-checkout)

  (when (magithub-usable-p)
    (-when-let (pull-requests (magithub-pull-requests))
      (magit-insert-section (magithub-pull-request-list)
        (magit-insert-heading "Pull Requests:")
        (mapc #'magithub-issue--insert pull-requests)
        (insert ?\n)))))
```
(added as an internal magit hook) and `magithub-feature-maybe-idle-notify` is defined so:
```elisp
(defun magithub-feature-maybe-idle-notify (&rest features)
  "Notify user if any of FEATURES are not yet configured."
  (unless (-all? #'magithub-feature-check features)
    (let ((m "Magithub features not configured: %S")
          (s "see variable `magithub-features' to turn off this message"))
      (run-with-idle-timer 1 nil (lambda () (message (concat m "; " s) features))))))
```
so I really don't see where it's getting all those extra symbols.

**Comment by gergelypolonkai** [comment]
Yes, adding `(magithub-feature-autoinject t)` to my init file did solve the problem.

**Comment by vermiculus** [comment]
If you feel up to it, can you do me a favor and instrument those functions with edebug (`C-u M-x eval-defun` on the form) and let me know how it goes? I still don't want this to be folks' default experience with magithub but without being able to reproduce the issue myself, my hands are somewhere tied. Where are all those extra symbols coming from?

**Comment by idcrook** [comment]
I do not know how to perform your request (related to `edebug`). However, this issue seems to have gone away after I changed my startup files to reflect what is on https://github.com/vermiculus/magithub#installation

changes below

```diff
diff --git a/.emacs.d/elisp/base-extensions.el b/.emacs.d/elisp/base-extensions.el
index d382380..e50c62b 100644
--- a/.emacs.d/elisp/base-extensions.el
+++ b/.emacs.d/elisp/base-extensions.el
@@ -286,8 +286,6 @@

 (use-package magit
   :config
-   ;; https://github.com/vermiculus/magithub
-   (use-package magithub)
    (use-package magit-popup)
   :bind
   ;; Magic
@@ -300,6 +298,12 @@
   ("C-x g r" . magit-rebase-interactive)
   ("C-x M-g" . magit-dispatch-popup))

+;; https://github.com/vermiculus/magithub
+(use-package magithub
+  :ensure t
+  :after magit
+  :config (magithub-feature-autoinject t))
+
 (use-package markdown-mode
   :ensure t
   :commands (markdown-mode gfm-mode)
```

**Comment by gergelypolonkai** [comment]
Something is really fishy here. Now I have removed the `magithub-feature-autoinject` call from my config (I’m sure I did it, as my `.emacs.d` is under version control), and the list of unconfigured features now contains only the two magithub features.

On a side note here, the warning says I should see the variable `magithub-features`, but the docstring of that variable doesn’t help much. Maybe you should change the word "see" to "set"?

**Comment by vermiculus** [comment]
@gergelypolonkai Indeed, that's really weird... I'll see what I can do about booting up a fresh vm to mimic the experience.

And really, I should just make the variable's documentation more helpful 😄 It should read something like this:

> An alist of feature-symbols to booleans indicating that feature's load-status
>
> For instance, if the alist contains a cons `(some-feature . t)`, the feature `some-feature` will be marked as loaded and you won't be nagged about it. If it's `(some-feature . nil)` or `some-feature` isn't the car of any cons in the alist, `some-feature` *isn't* loaded and you *will* be nagged.
>
> Use `magithub-feature-autoinject` to implement the features you desire.

**Comment by idcrook** [comment]
My emacs sessions last for days or weeks, so a couple more data points:

on another computer with earlier config (where `magithub` was loaded inside the `magit` config)
 1. re-launched emacs
 1. today used package manager to upgrade to both latest magit, magithub (magit-20170114.1211, magithub-20170115.1723)
 
Result: Do not see the issue.

Theory: Possibly related to initialization on package upgrade and how packages were configured to load in my init file.  

On computer that manifest issue under the "earlier" config (where the `use-package magithub` was within `use magit` `config:`), hadn't re-launched emacs, but _had_ upgraded magithub **after** an earlier (by a couple hours) package upgraded to magit in the same emacs session. It may have been sufficient just to re-launch emacs to not see the issue?  

And I suspect that the recommended way (using `after: magit`) described on https://github.com/vermiculus/magithub#installation will properly initialize magithub package...

Anyway, I am not seeing this issue anymore.

**Comment by vermiculus** [comment]
If it has something to do with compiling, then that might explain why I'm not seeing it. If you delete and reinstall magithub in a fresh emacs, does the issue come back?

**Comment by idcrook** [comment]
on machine with "earlier" version of my emacs init files

```
M-x package-delete magithub
# (exit emacs)
open /Applications/Emacs.app/
M-x package-install magithub
# do some magit operation on projects with github repos
```
do not see it.

```
M-x package-delete magithub
M-x package-install magithub
```
do not see it

**Comment by idcrook** [comment]
I'll close this as I am now unable to reproduce...

**Comment by gergelypolonkai** [comment]
It is still present on my side. I’m no Elisp Guru, but if you tell me how I can be useful bdebugging it, I’d be happy to do so.

Also, relying on users adding extra configuration just to avoid such annoyances is a no-go to me. IMHO you should either set that variable to a sane default, or not displaying a warning about it. Even if this bug wasn’t present, a short warning would still appear (with the correct values).

As I understand, this list holds the activated features of magithub. But what if I don’t want to use those features? I would empty the feature list, but in that case (again, if I get it right) I would face this message again.

**Comment by vermiculus** [comment]
@gergelypolonkai To disable all messages, just add `(add-to-list 'magithub-features '(t . t) t)`. As for the issue at hand, have you tried deleting and reinstalling the package to recompile it?

The idea was to get people to add the features they wanted without automatically injecting them into the rest of magit on load – [this was done at the request of magit's maintainer](https://github.com/vermiculus/magithub/pull/42#issuecomment-253773924). There's no good way to remove them once configured that I'm satisfied with yet, so I opted to opt-in instead of opt-out. 

Configuration like this is not at all uncommon in other emacs packages; this message just nags new users to explicitly enable or disable the features. I don't want the features to be ignored, but I also don't want to overstep my boundaries.

**Comment by gergelypolonkai** [comment]
How about warning the user about the fact **and** setting it to `(t . t)` (that looks like a smiley), so the user gets the warning only once per editor session, not after every Git operation? There was a similar feature in magit, they used the `magit-last-seen-setup-instructions` variable as a semaphore.

**Comment by vermiculus** [comment]
> not after every Git operation

Oh goodness! I didn't catch that it was doing it that often (since I've never been able to reproduce myself). I'll get this patched post-haste 😄

**Comment by vermiculus** [comment]
@gergelypolonkai See if the above works for you 😄

**Comment by vermiculus** [comment]
@idcrook -- why've you re-opened?

**Comment by idcrook** [comment]
it is still alive apparently? it is not because I am experiencing the issue.

**Comment by vermiculus** [comment]
Alright, just making sure!

@gergelypolonkai Does the above commit fix the 'lots and lots of messages' issue for you?

**Comment by gergelypolonkai** [comment]
Yes, it does.

The mesnage still contains pretty much all my installed features, but at least it’s only displayed once.

Recompiling the magithub directory doesn’t help, I remember someone asking that, too.
