### ISSUE TITLE
Document magithub-toggle-issues

### ISSUE THREAD

**Issue by Wilfred** [vermiculus/magithub#65]
I can't see any way of listing issues from the `H` popup.

I found `M-x magithub-toggle-issues`, but it doesn't seem to be included in the popup. `H i` only offers issue creation, and `H g` doesn't add issues to the magit UI.

Am I being stupid, or is this missing from the popup?

**Comment by vermiculus** [comment]
Issues should actually be inserted into the magit-status buffer automagically. When `hub` exists as magithub is loaded, we run

```elisp
(when (executable-find magithub-hub-executable)
  (magithub-toggle-pull-requests)
  (magithub-toggle-issues))
```

As far as actually toggling the sections, I guess I never considered they would be used from an interface. Personally I make heavy use of M-x for things that probably have keybindings that I just don't remember 😄

**Comment by Wilfred** [comment]
Aha, that's a good default behaviour. I didn't notice it because I hit #44.

Nonetheless, I think adding a toggle in the magit popup would help discoverability even further :). I'll try to write a PR.

**Comment by verdammelt** [comment]
The one small problem with that piece of code in `magit-issue.el` is
that it only runs if it can find the executable. The executable is in
the variable `magithub-hub-executable` which is defined in
`magithub.el` *after* `magithub-issue` is required.

So it never runs (unless I guess you are using Customize...). I think
this is why I've been having such trouble getting magithub to work and
have been quite confused :)!

I did a quick search but didn't find any sort of hook variable so I'll
probably do some sort of `(with-eval-after-load 'magithub ...)`thing.

Not sure if this sheds light onto the problems that @Wilfred was
having...
