### ISSUE TITLE
some simple prioritisation rules for PRs and issues

### ISSUE THREAD

**Issue by fommil** [vermiculus/magithub#67]
e.g. filter by assignee or a tag?

**Comment by vermiculus** [comment]
Do you think this would be better done in a new special issue-management buffer? I'm wary of introducing complexity into the status buffer.

**Comment by fommil** [comment]
yeah, maybe instead of "Pull Requests" and "Issues" there are "My ..." and users could selectively add those instead of the defaults.

I'd be perfectly happy with it just showing tickets I am assigned to, plus all PRs.
