### ISSUE TITLE
Add customization option to reverse sort order of issues and/or pull requests

### ISSUE THREAD

**Issue by dakrone** [vermiculus/magithub#71]
It would be really nice if there were a way to reverse the sort order of the issues and pull requests so that the higher number PRs/issues were at the top. I work on a repo with 1000+ issues and 100+ PRs open at any time, so having to scroll to the bottom to see the most recently opened ones is unfortunate.

**Comment by vermiculus** [comment]
As a workaround for now, just redefine [`magit-issue--sort`](https://github.com/vermiculus/magithub/blob/a94502461ada9098ccb031ec6241414dcbfce989/magithub-issue.el#L71).

**Comment by dakrone** [comment]
That works for now, thanks @vermiculus

**Comment by vermiculus** [comment]
@dakrone Does the above work for you?

**Comment by dakrone** [comment]
Seems to be working for me, thanks @vermiculus
