### ISSUE TITLE
Add option to disable "Pull Requests"

### ISSUE THREAD

**Issue by matthewbauer** [vermiculus/magithub#77]
# Feature Request

I'm currently using [magit-gh-pulls](https://github.com/sigma/magit-gh-pulls) to manage pull requests. I still would like to use magithub for its Issues tab. Is that possible? If not, can that be added as an option?

**Comment by vermiculus** [comment]
See [`magithub-toggle-pull-requests`](https://github.com/vermiculus/magithub/blob/0b5207f3097dee40feefea916cdf211734c9fe32/magithub-issue.el#L381). Does that not do what you want?

I'll note though that Magithub's pull request listing is about to get a major facelift:

![image](https://cloud.githubusercontent.com/assets/2082195/25921520/54521d96-359b-11e7-96d7-f2090c3f3f9f.png)

**Comment by matthewbauer** [comment]
Ok, I didn't see that. Does it actually "display" that tab before it's toggle off? I guess it's fine if that's the case, I just didn't want it to process anything it didn't need to.

**Comment by vermiculus** [comment]
If pull requests are turned off, the function that inserts them into the buffer is removed (and thus must make the request if necessary) is removed from a hook run on `magit-status`. No processing happens that doesn't need to happen 😄
