### ISSUE TITLE
There once was another magithub, but that's okay

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#8]
Just wanted to let you know that there once was another library called `magithub`: https://github.com/nex3/magithub/issues. It broke a long time ago and its author never deprecated the package or even just responded to the various issues that were opened due to that. Many issues were also opened against `magit` and `spacemacs` and elsewhere, causing a lot of work. Given that the original `magithub` is completely broken and likely will never be fixed I don't think it is a problem that you "steal" the name.

**Comment by vermiculus** [comment]
Oh, fancy that –  would you suggest any follow-ups on my end?

**Comment by tarsius** [comment]
Maybe add a little note to the readme?

**Comment by tarsius** [comment]
You might also want to update http://wikemacs.org/wiki/MagitHub.

**Comment by tarsius** [comment]
Okay, so I tried to try it. Unfortunately the `hub` installation instructions appear to be incomplete:

```
$ make install prefix=/usr/local
script/build -o bin/hub
/tmp/go/src/github.com/github/hub/github/config_decoder.go:7:2: cannot find package "github.com/BurntSushi/toml" in any of:
        /usr/lib/go/src/pkg/github.com/BurntSushi/toml (from $GOROOT)
        /tmp/go/src/github.com/BurntSushi/toml (from $GOPATH)
...
```

Any tips on that? They appear to think that I should know what the dependencies are and that I know enough about `go` to install them. That's not the case ;-(

**Comment by vermiculus** [comment]
I've updated the link you sent, thanks for catching 👍 

What OS are you working with? Unfortunately I only have experience installing the binaries on OSX with homebrew. I'll try installing on my debian vm and get back to you with what I find, but you may have better luck raising an issue on [github/hub](https://github.com/github/hub) -- from my experience, they have a pretty quick turnaround time for resolving issues.

**Comment by tarsius** [comment]
I've installed the damn binary ;-)

**Comment by vermiculus** [comment]
Working well, I hope? 😃
