### ISSUE TITLE
void-function ghubp--pre-process-params

### ISSUE THREAD

**Issue by xendk** [vermiculus/magithub#80]
Tried out the new version (20170514.754), but I get this:

```
Debugger entered--Lisp error: (void-function ghubp--pre-process-params)
  ghubp--pre-process-params(nil)
  ghubp-get-repos-owner-repo-issues(((owner (login . "xendk")) (name . "dotemacs")))
  eval((ghubp-get-repos-owner-repo-issues (quote ((owner (login . "xendk")) (name . "dotemacs")))))
  magithub-cache(:issues (ghubp-get-repos-owner-repo-issues (quote ((owner (login . "xendk")) (name . "dotemacs")))) "Retrieving issue list...")
  magithub--issue-list()
  magithub-pull-requests()
  magithub-issue--insert-pr-section()
  run-hooks(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-refresh()
  magithub-enable()
  magithub-enabled-toggle()
  funcall-interactively(magithub-enabled-toggle)
  call-interactively(magithub-enabled-toggle)
  magit-invoke-popup-action(96)
  funcall-interactively(magit-invoke-popup-action 96)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

I don't really get what's going on in ghub+.el. :-)

**Comment by vermiculus** [comment]
[This is being discussed on gitter right now;](https://gitter.im/vermiculus/magithub) something's funky. This shouldn't be happening (unless forms wrapped in `eval-when-compile` don't make it into the bytecode?)

**Comment by xendk** [comment]
So there's a chance I'll get the new and shiny magithub experience if I update tomorrow at work? Excellent. :-)

**Comment by vermiculus** [comment]
@xendk One way or another…

Do you happen to have any fancy ideas about how to convince elisp to keep certain forms in the byte compiled code?

**Comment by xendk** [comment]
Afraid not, I'm pretty newbie WRT elisp.

**Comment by vermiculus** [comment]
No fear, [Emacs.SE](https://emacs.stackexchange.com/q/3648/2264) is here 😄

**Comment by xendk** [comment]
:+1:

**Comment by vermiculus** [comment]
@xendk as a temporary workaround until melpa is updated, you can just evaluate `ghub+.el` interpreted (throw it in scratch and eval-buffer). Once the build is updated, that should work.
