### ISSUE TITLE
Some compile warnings

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#82]
Now that `hub` is no longer required, I have installed `magithub` again. I like it. Congratulations!

The performance issues that I used to had in my `.emacs.d` repository, which has many submodules, seem to be gone. But I ran into this:

```
magithub-issue-post.el:243:1:Warning: the following functions are not known to
    be defined: magithub-label-list, magithub-label-read-labels,
    magithub-issue-browse
```

**Comment by vermiculus** [comment]
That's odd, [we should be failing our tests then](https://travis-ci.org/vermiculus/magithub/jobs/232389331).

Just looks like some awkward loading going on; I'll take a look at it tonight.

**Comment by tarsius** [comment]
I found it surprising as well that this did not result in an error (or otherwise succeeded without any issues at all.)

> Just looks like some awkward loading going on;

I used my `borg` package manager. More specifically `make lib/magithub`, which results in `borg-build` being called, which in turn uses `borg-update-autoloads` and `borg-byte-comile` (in this case, and it also does a bit more, but that does not seem relevant).

**Comment by vermiculus** [comment]
Feel free to open this back up if it's still happening. Thanks for the report!

It seems like this was missed just based on the order the files were byte-compiled. Any crazy good ideas on how to combat that? My only thought is to try compiling each file in a standalone emacs process.
