### ISSUE TITLE
Use .github/ templates

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#9]
[GitHub released](https://github.com/blog/2111-issue-and-pull-request-templates) template files for issues and pull requests.  It would be stellar if Magithub used them as well.

**Comment by vermiculus** [comment]
Hm, this might be coming in the next version of `hub`: [`template.go`](https://github.com/github/hub/blob/d987f40f8d7572c6bdf555fe3e83a7d6ba281b3d/github/template.go). I can't find documentation for the code's purpose, but it seems like a fair bet this will do the work for me. I'll hold off on this for now.

**Comment by vermiculus** [comment]
This was fixed by 320047f743d175c1fab0364dff6328055dffe80d.

**Comment by piotr-yuxuan** [comment]
Thanks a lot @vermiculus for this contribution!

**Comment by piotr-yuxuan** [comment]
Is it possible to define local MagitHub templates?

**Comment by piotr-yuxuan** [comment]
Aw, I see I could use function ` (magit-toplevel)`.
